### ISSUE TITLE
在Ex Hentai裡只要搜尋一次之後，就無法再顯示任何其他搜尋了

### ISSUE THREAD

**Issue by Harbermas** [DaidoujiChen/Dai-Hentai#100]
D大你好，我在登入Ex Hentai帳號之後，
僅能夠使用搜尋一次，之後就再也無法搜尋到任何結果了。

當我下載or瀏覽完任何一本作品之後，
再切回去右上角搜尋頁面重新搜尋其他關鍵字，
但這次就無法顯示任何搜尋結果了。
App重啟也沒有用。
我推測這個BUG應該跟Ex Hentai連結的部份有關係，
但好像也無法登出Ex Hentai切回去一般的E 紳士。

我的版本是IPad pro / ios 9.3.3

請D大協助Debug，感恩！orz

**Comment by DaidoujiChen** [comment]
Hello @Harbermas 

看起來跟 #99 很像?

**Comment by DaidoujiChen** [comment]
@Harbermas & @Blake123

我還是沒有辦法重現你們的問題說, 我的步驟如下

 - 建立一個新的模擬器
 - 重新安裝這個 app
 - 利用列表左上的按鈕 `Exh` 登入
 - 成功後回到列表頁, 有顯示作品
 - 隨便點一本進去看, 然後退出
 - 在列表右上按放大鏡搜尋
 - 輸入要查詢的字 `moe`, 點右上的 `好`
 - 列表正常顯示
 - 然後重複, 在列表右上按放大鏡搜尋
 - 輸入要查詢的字 `c93`, 點右上的 `好`
 - 列表正常顯示

**Comment by Harbermas** [comment]
感謝回覆。

是的，我的步驟跟D大的一樣，
但App的確在搜尋過第一次有正常顯示之後，
第二次開始就無法顯示搜尋結果了...
會不會跟模擬器/平台之類的有關？
在實際的終端上無法refresh 搜尋結果之類的...

Ps.我在登入過EX-H之後，就無法再登出or切換回一般的E紳士了(i.e.左上角的Exh按扭消失）
這樣算正常嗎??

如上面所說，我的終端是IPad pro / ios 9.3.3 (盤古JB），
我之後再用iphone 6+ / ios 10.3.3試試，
看看能不能特定出問題徵結。

順帶一提，這個BUG在之前發佈的2.x沒有碰到過，
不過因為EX-H改了連結之類的設定，導致2.x的App無法抓到EX的資料，
所以變成必須要裝3.x...

再麻煩D大試試看了! orz

**Comment by DaidoujiChen** [comment]
@Harbermas 

ok, 我會再來試試, =w=, 就要變成砍掉我手機的 app 重新裝裝看了

登入 ExH 之後我是故意讓那個按鈕消失的, 因為 ExH 涵蓋了全部 EH 的內容, 想說應該不用有返回這件事 =w="

**Comment by DaidoujiChen** [comment]
@Harbermas 

目前登入 Ex 然後顯示的機制大概是這樣

 - 先讓使用者透過 `EH` 本身的網頁去做登入的動作
 - 在登入成功的時候, 會拿到一坨 cookies
 - 在對這些 cookies 做一些小幅度的修改之後, 這些 cookies 就可以拿到 `Ex` 使用
 - 接下來, 我們會去開啟 `https://exhentai.org/` 這個網址
 - 正常來說, 我們就可以看到列表 (我下面會附圖)

這個版本的調整, 在正常登入後, 在列表左上角多一顆按鈕 `CheckEx`
![simulator screen shot - ipad pro - 2018-03-10 at 23 36 33](https://user-images.githubusercontent.com/670441/37243939-98a7685a-24bc-11e8-8c5e-b529bfc54951.png)

然後點擊這個按鈕, `正常` 的情況下, 我們會可以看到 `Ex` 網頁的列表
![simulator screen shot - ipad pro - 2018-03-10 at 23 36 46](https://user-images.githubusercontent.com/670441/37243947-c0fa8bc0-24bc-11e8-8b71-d3e08e64a0a8.png)

這邊是一切的起源, 如果看不到列表的話, 一切就都白搭, 就有可能是牆內, 或是其他網路方面的問題了

免除拼來拼去的麻煩, 這邊我就直接附上這個測試版本的網址了

[https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.1_20180310/Dai-Hentai.ipa](https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.1_20180310/Dai-Hentai.ipa)

**Comment by wangtao03** [comment]
Ex搜尋結果正常
看來問題在於對得到搜尋結果和之後處理
如果日誌就好了

出問題時的網路包
[http://www.mediafire.com/file/778q3z034shd1nn/2_Full.txt](url)
正常情況下的網路包
[http://www.mediafire.com/file/8zat3s64xfgi5by/56_Full.txt](url)

**Comment by Harbermas** [comment]
@DaidoujiChen 

用ipad pro (ios 9.3.3)和 iphone 6+ (ios 10.3.3）分別測試了修正版，
問題還是一樣存在，
看樣子問題跟端末平台沒有關係。
我還測試了E紳士(i.e.未登入Ex)時的狀況，
然而這個BUG一樣存在...

至於新增的checkEx功能沒有問題，
即使搜尋結果無法顯示，
也可以切過去原始版的Ex-H，
所以也不是Ex帳號的問題。

可能跟 @wangtao03 講得一樣，
App跟E紳士、EX-H之間的訪問有問題吧。

**Comment by DaidoujiChen** [comment]
看了 @wangtao03 的兩個結果, 我大概知道問題出在哪邊, 但是你這個是用兩個不同的代理或是什麼樣的情形, 才可以產出兩種不一樣的結果嗎? 還是說 Ex 有時候會丟 `2_Full.txt` 有時候會丟 `56_Full.txt` 這種格式給你?

這邊大概解釋一下, `56_Full.txt` 檔案裡面, 我會抓一個
```
<div class="it5">
```
這樣的 html tag, 但是在 `2_Full.txt` 這個檔案裡面看起來沒這個東西, 他有的可能是
```
<div class="id2">
```
但是我沒辦法驗證 O口O"

**Comment by DaidoujiChen** [comment]
![2018-03-11 4 02 15](https://user-images.githubusercontent.com/670441/37251173-9e58ce04-2545-11e8-9a8c-7516173599d9.png)
我大概可以驗了, 差別大概是右下角的那個選項, 顯示列表或是顯示縮圖, 這樣我應該可以解了

**Comment by DaidoujiChen** [comment]
@Harbermas & @wangtao03 

好囉囉
來8

[https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.1_20180311/Dai-Hentai.ipa](https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.1_20180311/Dai-Hentai.ipa)

**Comment by Harbermas** [comment]
@DaidoujiChen 

可以正常使用了，
非常感謝!!

**Comment by DaidoujiChen** [comment]
看起來可以我就先關掉囉 >w< 感謝大家

**Comment by wangtao03** [comment]
感恩
