### ISSUE TITLE
[Bug]重新读已看的本子会导致程序崩溃

### ISSUE THREAD

**Issue by xingfanxia** [DaidoujiChen/Dai-Hentai#101]
因为有记忆上次这本本子读到了哪里，比如说上次读了80页就会提示从80页开始看。但是似乎默认预加载只有40页，然后点从80页开始看会崩溃（大概是想从缓存中找第80个index之类然后null pointer了）。

**Comment by DaidoujiChen** [comment]
Hello @xxf1995

請問是最新的版本嗎？

這個問題我好像有解過
https://github.com/DaidoujiChen/Dai-Hentai/commit/5f17a25b9e7d70181e72479d73f44e8b6c80012a

然後對應的是 #98 issue

**Comment by xingfanxia** [comment]
#92 fix那个版本，就在98之后

**Comment by DaidoujiChen** [comment]
蠔油 我再試試看 感恩

**Comment by DaidoujiChen** [comment]
Hello @xxf1995 

我測試了一下, 然後修改了一些犯蠢的 code, 這一個版本應該會是正常的了, 感恩 >x<

[https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.1_20180316/Dai-Hentai.ipa](https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.1_20180316/Dai-Hentai.ipa)

**Comment by xingfanxia** [comment]
ok 是解决了！

**Comment by DaidoujiChen** [comment]
Hello @xxf1995 

謝謝囉
