### ISSUE TITLE
Ex-H 無法觀看or下載

### ISSUE THREAD

**Issue by Harbermas** [DaidoujiChen/Dai-Hentai#102]
D大你好，

這次新修正的build號(20180313)突然無法觀看or下載Ex-H的檔案了，
檔案會卡在"DL: 0%"這裡不動。
測試過了不是網路問題，
直接進左上角的EX原始頁也可以正常開啟沒有問題，
我試著砍掉App重裝還是無解...

E紳士好像沒問題可以正常使用，
但進入Ex-H之後就不行了，
再麻煩D大協助了QQ

**Comment by DaidoujiChen** [comment]
Hello @Harbermas,

左上角有按鈕可以開啟網頁的版本應該是在修正前的呦, 後來已經把這個按鈕放到 setting 去了

[移除掉列表頁面左上方的 Ex 測試按鈕, 統一放到設定頁面中](https://github.com/DaidoujiChen/Dai-Hentai/commit/a927c51e7f6fd5b9f1826af61bdae72619ebd7a7)

你要不要確認一下用的 ipa 檔案是不是正確的, 感恩 O3Ob

**Comment by Harbermas** [comment]
@DaidoujiChen 
測試了最新版本20180315，
還是不行呢...
無法開啟or下載Ex-H的檔案QQ

**Comment by DaidoujiChen** [comment]
Hello @Harbermas 

所以列表顯示是 ok 的, 但是點進去隨便一本作品的時候, 無法正常顯示, 是這樣嗎?

**Comment by DaidoujiChen** [comment]
Hello @Harbermas 

應該是跟上次列表差不多的問題, 我調整了一個新的版本

[https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.1_20180316/Dai-Hentai.ipa](https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.1_20180316/Dai-Hentai.ipa)

你試試看如果行的話再說一聲, 這個 issue 就殻蟻關掉, 感恩

**Comment by Harbermas** [comment]
@DaidoujiChen 
這次沒問題了，萬分感謝! orz

**Comment by DaidoujiChen** [comment]
@Harbermas 

ok, 3qq, 那我關掉這個囉 >w<

fixed at https://github.com/DaidoujiChen/Dai-Hentai/commit/ea83f269567101615704bb80e4c2391a8e33e1c5
