### ISSUE TITLE
ios 12 gg了？ 闪退。。。

### ISSUE THREAD

**Issue by yriiolik** [DaidoujiChen/Dai-Hentai#103]
如图 3.x 版本

**Comment by codexss** [comment]
iOS12正常使用，没发现问题，另外啥时候把底部tab的icon加上，强迫症犯了

**Comment by DaidoujiChen** [comment]
還沒有升 12 的說 OwO

沒有設計師可以幫助加 icon
好可憐

**Comment by codexss** [comment]
直接网上找一下有非商用的icon可以拿来用吧，或者用Apple内置的_(:3」∠)_

发自我的 iPhone

**Comment by DaidoujiChen** [comment]
嗚嗚嗚 好

**Comment by yriiolik** [comment]
刷了ios12， 用impactor重新装了还是闪退， 奇怪了。 我去研究一下吧。。

**Comment by codexss** [comment]
我是在淘宝上买的udid签名文件然后用 appdb.to 签名装上的，没发现闪退。

**Comment by DaidoujiChen** [comment]
這個我就先關掉囉
tabbar 的 icon 我也加進去了
哈哈

**Comment by codexss** [comment]
NICE WORK，PS iOS 12 DB2 正常工作
