### ISSUE TITLE
有沒有iOS12安裝成功的？

### ISSUE THREAD

**Issue by BlueandwhiteXD** [DaidoujiChen/Dai-Hentai#105]
我的iOS12beta3（bate1也壹樣,2沒測試）使用Impactor成功安裝後，點進app閃退

**Comment by DaidoujiChen** [comment]
@BlueandwhiteXD 

OoO 我自己也還沒有升 12 不過上次好像有人說可以

**Comment by DaidoujiChen** [comment]
https://github.com/DaidoujiChen/Dai-Hentai/issues/103

這個

**Comment by BlueandwhiteXD** [comment]
@DaidoujiChen
谢谢，用Xcode装成功了

**Comment by DaidoujiChen** [comment]
所以有可能是 Impactor 在 iOS 12 上面還沒有很正常的運作 QwQ

**Comment by DaidoujiChen** [comment]
先關掉囉 >w<
