### ISSUE TITLE
你好，APP登录之后列表就无法抓取到数据了

### ISSUE THREAD

**Issue by HuberyQing** [DaidoujiChen/Dai-Hentai#108]
登陆之后就没有数据了，是什么BUG么

**Comment by DaidoujiChen** [comment]
耶? 我再試試
因為我自己每天也都有在用的說

**Comment by DaidoujiChen** [comment]
Hello @HuberyQing,

我用 iPhone7 iOS 12 模擬器試了兩次
感覺是 ok 的說

可以從設定頁面看一下頁面跟 API 的狀態
<img width="487" alt="2018-10-28 11 06 04" src="https://user-images.githubusercontent.com/670441/47611485-aead8f80-daa1-11e8-8cfe-629b70a0d8af.png">

或是點擊 `Ex 列表測試 (點擊開啟網頁)` 這個字樣
會嘗試是不是可以把頁面打開

<img width="487" alt="2018-10-28 11 07 52" src="https://user-images.githubusercontent.com/670441/47611500-e583a580-daa1-11e8-936a-17ffe97b7a3c.png">

像是這樣

**Comment by HuberyQing** [comment]
哦哦 我的EX列表测试 是熊猫图

**Comment by DaidoujiChen** [comment]
喔喔 有可能是你的帳號才剛申請不久嗎
我記得以前 eh 的帳號要放一段時間才可以去 ex

**Comment by DaidoujiChen** [comment]
Hello @HuberyQing,

那這個我要先關掉囉 OwO?
