### ISSUE TITLE
EH api 使用測試。不知道

### ISSUE THREAD

**Issue by xgztylm** [DaidoujiChen/Dai-Hentai#109]
如圖
![65b60a14-8021-42db-8b1b-38e54e742a88](https://user-images.githubusercontent.com/44933533/48307112-97ad7980-e546-11e8-972e-e6bd8c068209.png)
![60bc1ae9-84cd-4ca4-aac6-992916e7675d](https://user-images.githubusercontent.com/44933533/48307113-97ad7980-e546-11e8-9841-526b2f16109a.png)

**Comment by DaidoujiChen** [comment]
Hello @xgztylm,
牆內?

**Comment by HuberyQing** [comment]
我使用app的时候，在未登录状态下。列表是有数据的，但是如果登录之后，列表就无数据了，而且搜索也搜索不到数据

**Comment by HuberyQing** [comment]
![af8bb6ca-eb8e-4990-8088-8e4d67c157ba](https://user-images.githubusercontent.com/12196518/48338152-dc005d00-e69f-11e8-8865-787dac885655.png)
发现是这行代码的原因，只要登录默认就是EX，但是部分用户注册后却打不开EX....

**Comment by DaidoujiChen** [comment]
Hello @HuberyQing,

你的問題應該跟這個是不同的喔
按照上次的討論
你的帳號可能還註冊的不夠久
所以可能還不能去 ex

至於你這樣寫的話 就是使用一般的 eh 而已
醬

**Comment by DaidoujiChen** [comment]
明天來把登出鈕加進去
不然遇到進不去就沒輒的問題

**Comment by HuberyQing** [comment]
> 明天來把登出鈕加進去
> 不然遇到進不去就沒輒的問題

棒棒的~ 哈哈 遇到一个程序媛妹纸....

**Comment by DaidoujiChen** [comment]
@HuberyQing 
好棒

**Comment by DaidoujiChen** [comment]
我的一天快要變成人間七天了 =.=

**Comment by lancer1234** [comment]
有登出鈕的版本了嗎？

**Comment by xgztylm** [comment]
你好，我在西班牙居住，以前并没有问题

DaidoujiChen <notifications@github.com> 於 2018年11月12日 週一 04:11 寫道：

**Comment by DaidoujiChen** [comment]
Hello @lancer1234,

因為想把部分的 code 慢慢改成 swift 的版本
所以雖然看起來是做好了
但是我還是想多測測一下

**Comment by DaidoujiChen** [comment]
Hello @xgztylm,

好8, 因為如果不能登出的話, 其實沒有辦法替換新的 cookie 之類的 (只能等到他過期
或許你的問題也是重新登入就會好的

另外 你可以直接點那個開網頁的 按鈕
他會直接開啟網頁的版本
可以比較知道你現在的狀況

`一般` 來說 eh 應該是不會解析失敗的說

**Comment by xgztylm** [comment]
谢谢，我发现最近pad不管上什么网站经常都要我点“我不是机器人”的验证，好奇怪。导致测试的时候进入页面也是需要点红绿灯的状态，可能是因为这个。。。也不知道该怎么办。。。

DaidoujiChen <notifications@github.com>于2018年11月19日 周一上午4:08写道：

**Comment by DaidoujiChen** [comment]
Hello @xgztylm,

或許西班牙那邊的網路都是一群人共用一個 ip ?
都是同一個 ip 去某一個網站的時候 可能會被認為是機器人
才會需要有後續檢查你的動作
OwO

**Comment by HuberyQing** [comment]
> Hello @lancer1234,
> 
> 因為想把部分的 code 慢慢改成 swift 的版本
> 所以雖然看起來是做好了
> 但是我還是想多測測一下

我也是在将我司的工程转换swift的过程中

**Comment by DaidoujiChen** [comment]
這個 issue 我就先關掉囉
因為感覺是跟網路環境有關係的
OwO
