### ISSUE TITLE
安裝失敗 +搜尋閃退

### ISSUE THREAD

**Issue by fate955085** [DaidoujiChen/Dai-Hentai#114]
i6p ios12.0.1+ipad2017 ios10.3.3(jb)
使用cydia impactor無法安裝3.6版本
會出現cpp:42的錯誤
Delete App ID和revoke無效
ipad2017使用ReProvision安裝3.6和3.5版可以
但一搜尋本子就閃退，重開後會出現搜尋的內容
i6p使用cydia impactor可以安裝3.5版
不會出現搜尋就閃退的現象

這些有解嗎 qq

**Comment by CynicalHeart** [comment]
+1, 3.6版本无法安装 cpp:42错误。

**Comment by kkk682514** [comment]
+1 
3.6 版 Cpp 42 //砍掉重裝也一樣
3.5 版 正常

**Comment by zzysan** [comment]
看提示的意思好像是ipa已经被签名所以没有办法注入自己id的签名

**Comment by DaidoujiChen** [comment]
搜尋閃退指的是這件事情嗎 OwO?

https://github.com/DaidoujiChen/Dai-Hentai/commit/7864308b33ed41c2a22f2e34d193dcf5db5521c9

應該是有解了
不過還沒有 release 出來就是

**Comment by CynicalHeart** [comment]
感谢作者了，期待release上线

**Comment by DaidoujiChen** [comment]
安裝失敗我可能知道是什麼原因 o.o
但是好像沒有辦法解

過去的 ipa 檔案是我手動利用 itunes 把他轉出來
因為沒有經過發佈的流程 所以裡面的應該是 `開發` 憑證

後來 itunes 在 12.7.0 版本之後 把 Apps 頁籤拔掉
無法使用上述的方法拿到 ipa

取而代之的是 我放上的是 ad-hoc 版本的 ipa 檔案
裡面包的是 `發佈` 憑證

所以可能讓你們的軟體就無法 resign 他
QwQ

**Comment by DaidoujiChen** [comment]
上面打的是錯的..... =_____=
我後來都是從 `bitrise` 拿 ipa

我會把他放在這次 3.7 版本的 ipa 下載那邊
再請各位試試看.....
QwQ

**Comment by DaidoujiChen** [comment]
然後 `bitrise` 的顯示最近都是叉叉
因為 build 的時間不夠長了
好心人可以幫我隨便註冊一下下面這個網址
好像就可以延長 build 的時間

https://app.bitrise.io/users/sign_up?referrer=7ce4d42b591aa7b6

**Comment by kkk682514** [comment]
3.7已可安裝使用 感謝！
另外作者那個網址已註冊~
--------------
<題外求救>
有人Impactor 每七天重簽都會失敗嗎@@? (簽3個 Win10 Impactor 0.9.51)
之前七天 -> Impactor -> Revoke -> 重新拖拉ipa都沒問題
現在會出現cpp42 free account has reached maximum application (大概是長這樣吧)
Delete app id 也沒用 
請問有人有解嗎 還是我步驟錯了 google找不太到步驟@_@

**Comment by DaidoujiChen** [comment]
感謝 @kkk682514 幫安裝 OwO

Impactor 的問題不知道的說 QwQ

**Comment by DaidoujiChen** [comment]
這個我就先關掉囉 OwO
