### ISSUE TITLE
選擇原文時若搜尋欄空白會導致搜尋不到結果

### ISSUE THREAD

**Issue by hpigu** [DaidoujiChen/Dai-Hentai#115]
如題
選擇中文時若搜尋欄空白的話會正常顯示，可是如果是原文的話會找不到結果

**Comment by DaidoujiChen** [comment]
Hello @hpigu 
可以給個範例嗎
謝謝

**Comment by hpigu** [comment]
當我勾選原汁原味不翻譯、作品類別不限 皆會找不到作品

**Comment by DaidoujiChen** [comment]
@hpigu 
好喔 謝謝 我會去試試看

**Comment by DaidoujiChen** [comment]
Hello @hpigu,

我試完了
這個確實是這樣
如果 `沒有輸入搜尋關鍵字` + 勾選 `原汁原味不翻譯`
會沒有任何的內容

但是這個在原來的網站上行為就是這樣 QwQ
暫時沒辦法解決
