### ISSUE TITLE
历史和下载在ios9.3会显示空白的问题

### ISSUE THREAD

**Issue by acwqzy** [DaidoujiChen/Dai-Hentai#119]
找了下原因是fetchGalleries方法里的collectionView没有在主线程刷新的关系.

**Comment by DaidoujiChen** [comment]
Hello @acwqzy,

O口O" 3qq

**Comment by DaidoujiChen** [comment]
Hello @acwqzy,

確認了一下
在
`HistoriesViewController.m` 的 `fetchGalleries` reloadData 有在 main thread
<img width="1439" alt="2019-02-13 11 23 17" src="https://user-images.githubusercontent.com/670441/52684655-efaeae80-2f81-11e9-968e-265f18899dbb.png">

在
`DownloadedsViewController.m` 的 `fetchGalleries` reloadData 有在 main thread
<img width="1440" alt="2019-02-13 11 23 38" src="https://user-images.githubusercontent.com/670441/52685239-048c4180-2f84-11e9-9d5c-5da9d444fbf8.png">

我再檢查下其他部分

**Comment by acwqzy** [comment]
@DaidoujiChen 
我的锅,我这边用的还是老版本,下了新版本看下的确没这个问题了Σ( ° △ °|||)︴

**Comment by DaidoujiChen** [comment]
@acwqzy 
好喔 謝謝 那我把這個關掉囉 OwO
