### ISSUE TITLE
請求增加根據 URL 搜尋和匯出 URL 的功能

### ISSUE THREAD

**Issue by m13253** [DaidoujiChen/Dai-Hentai#120]
首先，感謝這個專案！

在使用這個 app 時我發現有一些不便，
比如其他人傳送給我 URL 我無法用 app 打開（只能先知道標題再搜尋），
我看到喜歡的漫畫無法分享給他人。

希望能在百忙之中考慮這兩項請求。
若您近期繁忙，不必現在就增加。

**Comment by DaidoujiChen** [comment]
我也想做 O口O

**Comment by DaidoujiChen** [comment]
喔喔 後面已經有加入分享按鈕惹 所以這個先關掉囉
