### ISSUE TITLE
Ex改版後 APP不能用 以及希望增加的功能

### ISSUE THREAD

**Issue by kkk682514** [DaidoujiChen/Dai-Hentai#122]
作者您好:
### 首先感謝作者讓我在這幾年有東西可以用XD
**☆Ex今天改版後 之前的API好像就不能用了**
當然這只是提個筆 不知道官方有沒有提供新的API
**☆據說某些本會鎖亞洲IP** 
實測用電腦上的確搜尋有49筆資料卻只有2筆資料跑出來
不知道用API的話 會不會被鎖到@_@
不過以前好像用APP看好像有 但用設置裡的網頁開就沒有 不知道是不是我的印象出錯了(?
**☆希望能增加備份的功能:**
希望能夠新增類似"會員"制度或是用icloud 在異地可以抓到下載/閱讀/搜尋紀錄(可能弄個本子ID之類的?
我之前看應用程式裡的檔案 好像不是圖片檔 不知道能不能手機下載後能夠傳到電腦看
感謝作者!!

**Comment by sdshdv** [comment]
这个是E站改版信息的汇总  :https://forums.e-hentai.org/index.php?showtopic=225016  希望尽快更新,ios端的E站客户端都不能用了

**Comment by anamewing** [comment]
作者刚才更新的版本我这里测试已经可以用啦
感恩

**Comment by DaidoujiChen** [comment]
Hello @kkk682514,

☆Ex今天改版後 之前的API好像就不能用了
-> 感覺只是網頁的介面有做調整 所以我看了一下 parse 的部分 小改一下應該已經可以看惹

☆據說某些本會鎖亞洲IP
-> 可以麻煩提供搜尋的關鍵字嗎? 我之前用 eh 的搜尋 有些本是因為設定成不公開 所以不會在列表上

☆希望能增加備份的功能:
-> 存的我記得是圖片的原始檔案

**Comment by carry0987** [comment]
Hello @DaidoujiChen  
那麼 iOS8 的使用者的2.X版本也可以用類似的方式修改parse囉?畢竟手機目前還是維持在 8.1.2....
小弟我先試試看能不能自行修改，目前正在學Swift中XD

**Comment by kkk682514** [comment]
@DaidoujiChen 作者好
☆Ex今天改版後 之前的API好像就不能用了
-> 感覺只是網頁的介面有做調整 所以我看了一下 parse 的部分 小改一下應該已經可以看惹
> 安裝新版後可以用了 非常感謝

☆據說某些本會鎖亞洲IP
-> 可以麻煩提供搜尋的關鍵字嗎? 我之前用 eh 的搜尋 有些本是因為設定成不公開 所以不會在列表上
> 一些關鍵字的測試可以看這篇:(像是 SummerHalation 或是 OneOne1)
https://www.ptt.cc/bbs/AC_In/M.1552988233.A.D49.html
https://www.ptt.cc/bbs/AC_In/M.1553006126.A.B38.html

☆希望能增加備份的功能:
-> 存的我記得是圖片的原始檔案
> 這我也忘記了QAQ 之前是有JB的時候看的
要實測可能要等之後 或是有其他JB用戶可以看一下

**感謝作者更新!!**

**Comment by kkk682514** [comment]
另外不知道有沒有機會引入Tag表(https://docs.google.com/spreadsheets/d/1_qmnx1HoxlxqrrC9dUbq1BHYbuXkOb8mszzMk84TUjk/edit#gid=1953436941)
雖然有點多 或是能直接加個"我的最愛"功能 把常打的TAG列出來

**Comment by yhc1994** [comment]
请问小改的在哪里能下载？Releases里的还是去年的版本

**Comment by kkk682514** [comment]
@yhc1994 
https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.7_20181210/Dai-Hentai.ipa

**Comment by yhc1994** [comment]
> @yhc1994
> https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.7_20181210/Dai-Hentai.ipa

多谢。我试了一下这个新版本EX列表/API都显示成功但是事实上在APP里是搜不到EX的内容的，只有EH的内容，大家都是一样的吗

**Comment by yhc1994** [comment]
在设置里打开的网页里，EX内容都是可以搜索到的，但是用APP搜索就搜索不到任何EX的内容

**Comment by DaidoujiChen** [comment]
Hello @yhc1994,

我一直都在 ex 裡面的說
可以貼一下 `在设置里打开的网页里` <- 的截圖嗎
感恩

**Comment by carry0987** [comment]
Hello @DaidoujiChen  我剛剛去Ex看了一下，他好像改成"**gl3m glname**"欸，不是"**gl3c glname**"

**Comment by DaidoujiChen** [comment]
@carry0987 
現在在上班沒辦法去看 QwQ
但是我猜想會不會是跟以前一樣 
顯示的方式會有點不一樣 (比方說 列表呈現 / 塊狀圖片呈現 之類的
所以造成 class 名稱不同

**Comment by kaho2205** [comment]
感謝開發大佬在改版後努力改進app,另外我是不是可以期待一下2.X也能修復呢

**Comment by DaidoujiChen** [comment]
2.x @carry0987 這兩天有發一個 pr
https://github.com/DaidoujiChen/Dai-Hentai/pull/123
假日的時候我會找時間把 ipa 生出來

**Comment by carry0987** [comment]
@DaidoujiChen  感謝大大!!
話說回來，要不要乾脆把`~/Models/HentaiParser/HentaiParser.m`這個檔案中的
```
NSArray<TFHppleElement *> *photoURLs = [xpathParser searchWithXPathQuery:@"//td [@class='gl3c glname']//a"];
```
後面`parse`的部分變成可編輯?這樣就不用每次改css都特地弄一個新的IPA，比如讀取一個名字叫做`ParseSet.list`的檔案，裡面只有一行 :
```
td [@class='gl3c glname']
```

**Comment by DaidoujiChen** [comment]
> Hello @DaidoujiChen 我剛剛去Ex看了一下，他好像改成"**gl3m glname**"欸，不是"**gl3c glname**"

<img width="1423" alt="螢幕快照 2019-03-24 下午8 46 29" src="https://user-images.githubusercontent.com/670441/54879617-f3cdc600-4e75-11e9-94f0-019b645254ff.png">

看了一下阿 跟選擇顯示的樣式有關係 OwO
3.0 目前預設帶的是 `inline_set=dm_l` 他的 class 就會是 `gl3c glname`

**Comment by DaidoujiChen** [comment]
@kaho2205, @carry0987 

https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/2.64_2.64/e-Hentai.ipa
這個是 bitrise 幫我 build 2.x_master branch 生出來的 ipa

我只有用模擬器測過 看起來是可以看見列表
但還是請你們先備份目前手上的版本比較保險喔 OwOb

**Comment by carry0987** [comment]
Hello @DaidoujiChen  ,測試完成，一切OK，就算我的Web端改成Thumbnail，手機那邊依然可以正常顯示
唯一的小問題就是APP沒有icon而已XD

**Comment by carry0987** [comment]
> > Hello @DaidoujiChen 我剛剛去Ex看了一下，他好像改成"**gl3m glname**"欸，不是"**gl3c glname**"
> 
> <img alt="螢幕快照 2019-03-24 下午8 46 29" width="1423" src="https://user-images.githubusercontent.com/670441/54879617-f3cdc600-4e75-11e9-94f0-019b645254ff.png">
> 
> 看了一下阿 跟選擇顯示的樣式有關係 OwO
> 3.0 目前預設帶的是 `inline_set=dm_l` 他的 class 就會是 `gl3c glname`

原來如此，懂了~

**Comment by carry0987** [comment]
@DaidoujiChen  剛剛看了一下，只少了 **`AppIcon`** 而已~

**Comment by Kennnnnnji** [comment]
新版的可以用啦，感谢开发！还有就是能不能加入同步网页版的收藏夹的功能呢，辛苦大大~

**Comment by DaidoujiChen** [comment]
附帶一件事情 昨天已經把 branch 2.x 接上 ci 惹
所以未來如果你們有想在 2.x 上面改什麼
發 pr 去那個 branch
ipa 就會自動生長出來惹

許願的部分要可能就要等我有時間惹 QwQ
通常我會以不能用當作要不要馬上改的基準 (因為我也不能看了阿 O口O"
哈哈

**Comment by carry0987** [comment]
@DaidoujiChen  大大，App的icon部分你有提到過這句話
`不過礙於內容尺度的關係, 並沒有將圖片內含在這個專案的資料夾內`
那麼，如果我要加上去，用PR好像也不太好?(2.X)
(目前的App在screen上是一個白色的正方形)

**Comment by DaidoujiChen** [comment]
Hello @carry0987 ,

我想是因為那時候的進場圖尺度太大
如果只是 icon 的話應該還好
看你想用粉紅色的那個或是藍色的那個都行 OwOb

**Comment by carry0987** [comment]
大大，這裡有個問題回報，我沒辦法進入第二頁，一旦點選下一頁，就會出現讀取失敗，然後會連第一頁都無法載入，除非我手動刪除cookie資料夾的那個binary檔案，但是這樣依然只能看到第一頁的搜尋結果...這樣的問題僅出現在Ex的部分
-- 
By Carry

**Comment by carry0987** [comment]
Hello @DaidoujiChen  
大大，這裡有個問題回報，我沒辦法進入第二頁，一旦點選下一頁，就會出現讀取失敗，然後會連第一頁都無法載入，除非我手動刪除cookie資料夾的那個binary檔案，但是這樣依然只能看到第一頁的搜尋結果...這樣的問題僅出現在Ex的部分

**Comment by carry0987** [comment]
嗯？等等，如果在載本的同時搜尋，那連Eh都會有一樣的「無法載入」的問題

**Comment by DaidoujiChen** [comment]
Hello @carry0987,

我測了一下 2.x 好像不會耶
會不會是你載的太兇惹
被暫時鎖 ip 之類的 (?

**Comment by carry0987** [comment]
@DaidoujiChen  我再試試看，不過我的Xcode會一直瘋狂提醒我要更新某些代碼，比如 `(void)` 之類的，但是加上去之後反而有更多錯誤XD，可能Xcode不喜歡 Objective-C 而偏好Swift吧...(?

對了大大，我的Xcode會一直告訴我realm有新版本之類的訊息，這是我跑模擬2.X的時候在console看到的，需要在意嗎?

**Comment by DaidoujiChen** [comment]
@carry0987 如果還可以動 就不用管他 OwO

**Comment by tonolshiki** [comment]
bitrise上新版的ipa有更新吗？

**Comment by tonolshiki** [comment]
新版的ipa大概什么时候能有？

**Comment by DaidoujiChen** [comment]
太長惹
先關掉這個 issue 囉
OwO
