### ISSUE TITLE
[功能建议]itune文件导出,文件app支持,缓存后缀名

### ISSUE THREAD

**Issue by kongdayan** [DaidoujiChen/Dai-Hentai#124]
感谢大佬开发的app造福我们(・ω・)ノ
下面正题:
原因:
        有时候忘记重签app就打不开了，在外使用不便
建议:
       增加itunes文件导出功能
       ios ‘文件’ app 访问功能 
       图片缓存添加后缀名
个人的解决方案:
      如果想要在itunes文件导出已下载的内容则需要在info.plist 里添加 UIFileSharingEnabled YES
      想要在ios 文件app 中打开则需要添加Supports opening documents in place YES
参考链接 https://www.appcoda.com/files-app-integration/
      图片缓存时没有后缀名,导出后需要批量重命名很麻烦,我自己写了一个添加后缀名的版本但是无法在app内直接看，只能走文件app了，就不放出来出丑了。。。。效果如图
![IMG_5731](https://user-images.githubusercontent.com/19552144/54743181-6f254280-4bfe-11e9-81c2-6c58d7f4d370.PNG)
![IMG_5732](https://user-images.githubusercontent.com/19552144/54743045-063dca80-4bfe-11e9-9a13-c46e08c53280.PNG)
![IMG_5733](https://user-images.githubusercontent.com/19552144/54743109-38e7c300-4bfe-11e9-8f26-005b324d50e8.PNG)

**Comment by DaidoujiChen** [comment]
好強喔 OoO
我來試試

**Comment by DaidoujiChen** [comment]
昨天想了一下阿
我覺得讓 itunes 可以同步檔案到電腦 ok
但是同時 share 到 `Files` <- 這個 app 感覺就有點疑慮
因為就違背了 app 上鎖的功能 QwQ
就會變成上了鎖還是可以從 `Files` 去看
不知道大家有沒有什麼想法

**Comment by kkk682514** [comment]
我也覺得Files不要出現比較好

**Comment by DaidoujiChen** [comment]
有安全性的疑慮 (?
