### ISSUE TITLE
为什么界面都找不到作品，解析也错误，明明登陆上账号了

### ISSUE THREAD

**Issue by hentaisama** [DaidoujiChen/Dai-Hentai#125]

**Comment by DaidoujiChen** [comment]
Hello @hentaisama,

請問用的是哪一個版本捏?

**Comment by hentaisama** [comment]
3.7版本,最新的那个，其它的版本我也试过，但都不行

**Comment by DaidoujiChen** [comment]
那你從最後一個 tab 的網頁跟 api 狀態那邊看到的訊息是什麼
可以點擊那邊的字樣開啟網站看看嗎

**Comment by jyz1022** [comment]
我也是，测试分别是
EH 解析失败
EH API 不知道
EX 解析失败
EX API 解析失败

**Comment by hentaisama** [comment]
eh解析失败，和上面那位一样，但是e站网页可以打开

**Comment by DaidoujiChen** [comment]
喔喔喔喔喔 我大概知道惹

請你們用下面這個連結的 ipa 檔案吧

https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.7_20181210/Dai-Hentai.ipa

release 那邊的內容因為我沒有跳版號 所以一直沒去更新 QwQ

**Comment by hentaisama** [comment]
哦哦，可以了，原来是改版了吗，icon都不一样了

**Comment by DaidoujiChen** [comment]
那我又要來關掉囉
OwO 
改天我再來去跳 release 那邊的版本號
