### ISSUE TITLE
列表會因沒有關鍵字變成找不到作品

### ISSUE THREAD

**Issue by gabmak** [DaidoujiChen/Dai-Hentai#128]
太感動了 以前一直在iPad mini 2 ios 8 上用v2 現在大大更新了最近的E-h改版令我更想買新iPad

我剛剛在Similuatior 上面試，發現如果在搜尋的時候只選原汁原味 其他空着的，會因為關鍵字是空白導致列表變成找不到作品 T︿T

是不是要加個if去看如果關鍵字是空的&&原汁原味的就直接無視原汁原味...

![螢幕截圖 2019-04-19 22 05 38](https://user-images.githubusercontent.com/22220745/56425482-80419c00-62ef-11e9-8e87-e7c33561372c.jpg)

![螢幕截圖 2019-04-19 22 24 14](https://user-images.githubusercontent.com/22220745/56426091-e0d1d880-62f1-11e9-8df9-959eb8a0606c.jpg)

**Comment by DaidoujiChen** [comment]
喔喔 這個原因是勾了 `原汁原味不翻譯`

**Comment by DaidoujiChen** [comment]
所以我就先關掉囉 OwO
這算是原來官方的搜尋就存在的問題
