### ISSUE TITLE
【安裝問題】使用mac安裝的時長限制

### ISSUE THREAD

**Issue by LiuZHolmes** [DaidoujiChen/Dai-Hentai#129]
因爲平常使用的是Windows系統，每次安裝都只能使用七天。想問一下有Mac的朋友安裝后時長有限制嗎？安裝過程中需要付費購買蘋果的開發者賬戶嗎？

**Comment by m13253** [comment]
不需要付費購買開發者賬戶。
但是也有七天的限制。

**Comment by DaidoujiChen** [comment]
就是這樣 喵!
