### ISSUE TITLE
试图使用xcode安装，但是一直build failed

### ISSUE THREAD

**Issue by yuanwenbin36** [DaidoujiChen/Dai-Hentai#130]
<img width="374" alt="屏幕快照 2019-05-02 下午10 21 07" src="https://user-images.githubusercontent.com/15710468/57117244-a2dca780-6d28-11e9-83a5-8ba1ef280de3.png">
反复出现这个报错，请问应该如何解决？

**Comment by DaidoujiChen** [comment]
如果你有自己的開發者帳號的話 把 `tw.daidouji.Dai-Hentai` 這個 id 換成一個你喜歡的

**Comment by DaidoujiChen** [comment]
先關掉囉
OwO
