### ISSUE TITLE
需要登录账号吗？

### ISSUE THREAD

**Issue by dustturtle** [DaidoujiChen/Dai-Hentai#131]
我没有自己的账号，之前没登录也可以用的。最近用不起来了（都显示解析失败什么的），请问一下什么情况哈？

**Comment by dustturtle** [comment]
@DaidoujiChen

**Comment by DaidoujiChen** [comment]
可能你沒有裝最新的版本 (?

https://github.com/DaidoujiChen/Dai-Hentai/releases/tag/v3.8_20190411

`因為 eh / ex 網頁改版導致 parse 失效的問題` <-

**Comment by dustturtle** [comment]
我确实没装新版本。 谢谢啦 @DaidoujiChen
