### ISSUE TITLE
iOS13闪退

### ISSUE THREAD

**Issue by yhc1994** [DaidoujiChen/Dai-Hentai#132]
升级ios13之后，每次进入app，一秒后就会闪退
用的是release里的最新版本v3.8_20190411

**Comment by yhc1994** [comment]
并不是立即闪退，每次打开能看到app里的内容很短的一段时间，然后才会闪退

**Comment by DaidoujiChen** [comment]
OoO

**Comment by DaidoujiChen** [comment]
裝了 xcode 11, 用模擬器試了一下 好像 ok
會繼續追蹤

**Comment by yhc1994** [comment]
BETA2修复了

**Comment by DaidoujiChen** [comment]
阿阿 這個我忘記關掉惹
謝謝你
