### ISSUE TITLE
能否增加一个重新载入按钮？

### ISSUE THREAD

**Issue by Golubb** [DaidoujiChen/Dai-Hentai#133]
经常遇到图片加载不出的情况，是否可以考虑增加一个重新载入按钮？

**Comment by DaidoujiChen** [comment]
機制上阿 如果滑到那種壞掉的圖片的時候
我在背後是會再去做一次拉圖片的動作
如果滾來滾去那張圖片都還是壞的
可能就是真的拉不到那張圖

**Comment by DaidoujiChen** [comment]
先關掉囉 OwO
