### ISSUE TITLE
熊貓好像要跟這個世界說再見了

### ISSUE THREAD

**Issue by DaidoujiChen** [DaidoujiChen/Dai-Hentai#134]
https://sora.komica.org/00/pixmicat.php?res=15445345&fbclid=IwAR36Pb0dGuGLndI7usClxzDymnYShBpk4DBMI78yAdeuHEcaejFKH2pjui0

**Comment by hpigu** [comment]
上午才剛說下午就關了QQ

**Comment by DDVD233** [comment]
感覺好突然啊

**Comment by DaidoujiChen** [comment]
神慘的

**Comment by hpigu** [comment]
好像又復活了（？

**Comment by DDVD233** [comment]
确实复活了。App 实测可用

hpigu <notifications@github.com>於 2019年8月2日 週五，下午7:17寫道：

**Comment by yhc1994** [comment]
> 确实复活了。App 实测可用 hpigu <notifications@github.com>於 2019年8月2日 週五，下午7:17寫道：
> […](#)

为啥我这里不行，点登陆只能载入几个动漫人鞠躬的图片

**Comment by DaidoujiChen** [comment]
我這邊也復活惹說
