### ISSUE TITLE
Dark mode 下列表显示不正常

### ISSUE THREAD

**Issue by StoneMoe** [DaidoujiChen/Dai-Hentai#136]
在 Dark mode 下，列表底色与文字颜色均为白色。

**Comment by DaidoujiChen** [comment]
嗚嗚嗚 還沒進 iOS13

**Comment by StoneMoe** [comment]
虽然不是iOS开发，不过试着使用Named Color替换了一些颜色选项....

（只能用于 iOS 11 以上）

**Comment by DaidoujiChen** [comment]
在

https://github.com/DaidoujiChen/Dai-Hentai/pull/148

應該修正這個問題惹
OwOb
