### ISSUE TITLE
为什么应用在安装几天之后就会闪退?

### ISSUE THREAD

**Issue by veyyyyyyy** [DaidoujiChen/Dai-Hentai#143]
大佬你好,

按照文中的方法安装之后,app在开始的时候可以正常使用;但是过了几天(大概一周)之后就会闪退,重新安装便可再度使用一段时间,已经重复好几次了(捂脸);有没有解决的方法呢,感谢~

(iPhone 8, iOS 13.1.3;mac和xcode均是最新系统)

**Comment by DaidoujiChen** [comment]
@chiahao214,

如果是用個人沒有付費的帳號 sign 的話
憑證好像只能活一週

**Comment by DaidoujiChen** [comment]
https://forums.developer.apple.com/thread/91519

```
Free provisioning (no paid developer account) is good for one week.
```

**Comment by veyyyyyyy** [comment]
@DaidoujiChen 感謝你的答疑

**Comment by DaidoujiChen** [comment]
那我就先關掉囉
