### ISSUE TITLE
[功能建议] 希望增加清除缓存功能

### ISSUE THREAD

**Issue by kyloris0660** [DaidoujiChen/Dai-Hentai#144]
浏览产生的数据缓存目前似乎只能通过删除app清除，希望可以在用量界面增加清除cache的功能。
非常感谢ORZ

**Comment by gabmak** [comment]
這個問題暫時可以透過過刪除歷史解決...

**Comment by DaidoujiChen** [comment]
喔喔 對 謝謝 @gabmak 幫我回答
還是說 @kyloris0660 希望的是可以清掉套件做的圖片緩存

**Comment by kyloris0660** [comment]
非常感谢 前面没有发现历史记录可以解决。。
