### ISSUE TITLE
Bitrise下载失败

### ISSUE THREAD

**Issue by RedDevi1s** [DaidoujiChen/Dai-Hentai#146]
按照格式得到的最新版本的地址为
http://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.10_20191225/Dai-Hentai.ipa
结果报错了哦

**Comment by DaidoujiChen** [comment]
喔喔 抓版本號碼跟 build 號的地方可能有些問題
我再找時間調整下

**Comment by DaidoujiChen** [comment]
調整過 bitrise 的 workflow 後已修正這個問題
