### ISSUE TITLE
exkey是什么？

### ISSUE THREAD

**Issue by epnode** [DaidoujiChen/Dai-Hentai#147]
感谢大大已编译成功，可是如何登入呢？

**Comment by DDVD233** [comment]
在设定->eh列表测试（点击开启网页）处可以开启网页进行登录，cookie会自动保存下来。

exkey是用来快捷登录用的，格式为
ipb_pass_hash+ipb_member_id+'x'+igneous

**Comment by DaidoujiChen** [comment]
謝謝 @zjdavid

**Comment by DaidoujiChen** [comment]
@epnode 

先關掉囉~~~~~

**Comment by epnode** [comment]
'x'应填入什么参数？

**Comment by DDVD233** [comment]
> 'x'应填入什么参数？

就是字母'x'，分割用的
