### ISSUE TITLE
cydia impactor 目前无法安装

### ISSUE THREAD

**Issue by VVVVictorJ** [DaidoujiChen/Dai-Hentai#149]
![image](https://user-images.githubusercontent.com/38826071/72661878-9a451200-3a1a-11ea-9f9f-1e8de2e6d43e.png)
![image](https://user-images.githubusercontent.com/38826071/72661891-ceb8ce00-3a1a-11ea-8a12-507f4445f2bf.png)
@DaidoujiChen 可以更新下readme，提醒下大家

**Comment by VVVVictorJ** [comment]
关键意思是12月中之前都没有办法完善cydia impactor ，现在是一月18了。估计还是要等作者更新才行。
目前还是只能mac上xcode 或者vm上xcode安装，-_-''

**Comment by shinrenpan** [comment]
可以試試用
[AltDeploy](https://mrmad.com.tw/altdeploy)
[AltStore](https://mrmad.com.tw/altstore)
安裝

**Comment by DaidoujiChen** [comment]
我把 readme 調整過惹
感謝兩位的資訊

@VVVVictorJ 
@shinrenpan 

OwOb
