### ISSUE TITLE
用xcode的时候显示"Dai-Hentai" requires a provisioning profile.

### ISSUE THREAD

**Issue by pudding2718** [DaidoujiChen/Dai-Hentai#151]
如果关闭Automatically manage signing会显示"Dai-Hentai" requires a provisioning profile.

如果打开Automatically manage signing会显示Signing for "Dai-Hentai" requires a development team.如果把team选为自己的苹果id又会显示Failed to register bundle identifier.和No profiles for 'tw.daidouji.Dai-Hentai' were found

请问是要怎么办呢

**Comment by DaidoujiChen** [comment]
用 auto
team 選成你自己的
然後名字取一個你喜歡的 (?

**Comment by pudding2718** [comment]
> 用 auto
> team 選成你自己的
> 然後名字取一個你喜歡的 (?

请问是在signing & capabilities下面么？
我选了Automatically manage signing，tema选成了自己
但是会变成图片这样
[https://i.imgur.com/8mBBvCk.png](https://i.imgur.com/8mBBvCk.png )

**Comment by pudding2718** [comment]
抱歉 第一次用xcode 
orz

**Comment by DaidoujiChen** [comment]
@pudding2718 

你把 `tw.daidouji.Dai-Hentai` 換成別的名字試試
OwO

**Comment by pudding2718** [comment]
换成什么都没有用😭
是要自己去apple注册一个Bundle ID嘛

**Comment by DaidoujiChen** [comment]
應該是不用吧 (?
後來 xcode 應該都可以自動幫你用到完

**Comment by pudding2718** [comment]
那有什么换成的建议吗？
或者是apple账号得是台服吗？我的是美服的

**Comment by DaidoujiChen** [comment]
應該是沒差吧 OwO?

**Comment by Himitsu98** [comment]
把 bundle identifier 改成一个很复杂的即可，因为这个标识符要求唯一，比如com.fucking123333
