### ISSUE TITLE
无法正常下载图片了，封面可以

### ISSUE THREAD

**Issue by dustturtle** [DaidoujiChen/Dai-Hentai#156]
提示bandwidth exceed之类的

**Comment by dustturtle** [comment]
![D4398FBE-84EC-4E62-ADD6-221D6B0535CA](https://user-images.githubusercontent.com/2305214/90039303-06f66580-dcf9-11ea-91e4-e9919a396e6e.png)

**Comment by dustturtle** [comment]
![B5F863F8-D15D-41D6-84D2-63FF12704CB3](https://user-images.githubusercontent.com/2305214/90039437-34dbaa00-dcf9-11ea-803e-959fc9407539.png)

**Comment by DaidoujiChen** [comment]
Hello @dustturtle,

是因為大量下載被 ban 掉惹嗎?

**Comment by Ahtaler** [comment]
换条线试试

**Comment by DaidoujiChen** [comment]
這個我就先關掉囉 OwOb
