### ISSUE TITLE
虽然Bitrise Passing但是里边不含任何版本号

### ISSUE THREAD

**Issue by Ahtaler** [DaidoujiChen/Dai-Hentai#157]
可能是对接接口失效了？请求修理一下。

**Comment by Ahtaler** [comment]
早几个月并没有这样的，是最近出现的问题。

**Comment by DaidoujiChen** [comment]
我記得我好像修好惹 ( ?
我看看下鷗

**Comment by DaidoujiChen** [comment]
最新的應該是這個

https://dai-hentai-ipa.s3-ap-northeast-1.amazonaws.com/bitrise/3.10_20191225/Dai-Hentai.ipa

**Comment by DaidoujiChen** [comment]
這個我也關掉囉 OwOb

**Comment by Ahtaler** [comment]
DaidoujiChen <notifications@github.com>于2020年8月31日 周一下午1:20写道：

>
>
>
> 我記得我好像修好惹 ( ?
>
>
>
> 我看看下鷗
>
>
>
>
>
>
> —
> 好的，谢谢DaidoujiChen！
>
