### ISSUE TITLE
Bitrise又报错了啦QAQ

### ISSUE THREAD

**Issue by Ahtaler** [DaidoujiChen/Dai-Hentai#159]
出错了，另外请问有没有新版本呢？
用Xcode安装是不是可以不用Jailbreak就可以直接使用了呢？

**Comment by DaidoujiChen** [comment]
對 用 Xcode build 的話就不用 jb 惹

**Comment by DaidoujiChen** [comment]
bitrise 應該是我的憑證過期了 沒有上傳新的

**Comment by Ahtaler** [comment]
蟹蟹你！(´･Д･)」
