### ISSUE TITLE
请问现在一定要翻墙才能看吗？不然一直显示列表为空？

### ISSUE THREAD

**Issue by 302766440** [DaidoujiChen/Dai-Hentai#160]
我的版本是3.8，请问是否最新版本？现在翻墙才能看，是不是和版本有关？我不知道怎么下载新版本。。你写着获取beta版本需要有版本号和建立号，可是我点开两个链接后发现不知道怎么看、、跪求解答。

**Comment by 302766440** [comment]
你写着获取beta版本需要有bb号和jl号，可是我点开两个网址后发现不知道怎么看、、跪求解答。

**Comment by DaidoujiChen** [comment]
Hello @302766440,

我猜最新版本的連結是

https://dai-hentai-ipa.s3-ap-northeast-1.amazonaws.com/bitrise/3.10_20191225/Dai-Hentai.ipa

但是我不知道是不是要翻牆才可以的說
你可以點設定那邊
會有可以直接開一個網頁測試看看

如果你在牆內連網頁都打不開的話
app 就也一樣無法惹
QwQ

**Comment by 302766440** [comment]
> 您好@30276640，
> 
> 我猜最新版本的連結是
> 
> https://dai-hentai-ipa.s3-ap-northeast-1.amazonaws.com/bitrise/3.10_20191225/Dai-Hentai.ipa
> 
> []牆說]點設
> 
> 邊邊會] 開個網頁測試
> 
> [牆內連網頁] 開話
> = 樣無
> Qwq

非常感谢你，更新到最新版，很遗憾还是得翻墙才能看到。我记得很久前有一次也是这样，更新了就好了。这一次好不了了。。我估计是这个ex网站的问题。。主要是翻墙看加载非常缓慢，图片要等很久才能出来，而且不齐全。。呜呜呜我哭了
不知道神奇的网友们有没有什么方法

**Comment by DaidoujiChen** [comment]
Hello @302766440,

牆內不知道的說.....
沒有去過牆內
