### ISSUE TITLE
请问在哪里下载？

### ISSUE THREAD

**Issue by yu197817** [DaidoujiChen/Dai-Hentai#164]
最新版本的阅读器

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by hyperventilated** [comment]
hello

**Comment by DaidoujiChen** [comment]
ipa 在這邊

https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.11_20221117/Dai-Hentai.ipa
