### ISSUE TITLE
請問IPA下載是不是取消了

### ISSUE THREAD

**Issue by klawchi** [DaidoujiChen/Dai-Hentai#167]
因為舊版本有內容不停重覆的問題, 所以上來看一下有沒有新版本, 但release只有看到3.8版本的, bitrise也只有一個x連3.10版也找不到
謝謝

**Comment by kkk682514** [comment]
同問 
現在開app似乎只有搜尋結果第一頁的內容
再麻煩作者更新了
感恩

**Comment by yhc1994** [comment]
作者已经在最新的repo里修复了，但是没有发布ipa，没有mac就装不了

**Comment by DaidoujiChen** [comment]
我忘惹之前是怎麼包的惹
但是感覺是有點壞掉

如 @yhc1994 說的
我自己也遇到一直同一頁的問題惹
所以我有直接把他修掉 OwOb

**Comment by DaidoujiChen** [comment]
修好惹

https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.11_20221117/Dai-Hentai.ipa

**Comment by 302766440** [comment]
> 修好惹
> 
> https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.11_20221117/Dai-Hentai.ipa

点不开啊作者大大。点击后显示该网页无法显示

**Comment by DaidoujiChen** [comment]
> https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.11_20221117/Dai-Hentai.ipa

OwO? 應該是可以下載的說
