### ISSUE TITLE
请问怎么安装啊？没有ipa文件啊

### ISSUE THREAD

**Issue by 302766440** [DaidoujiChen/Dai-Hentai#168]
作者大大，求求告知怎么转成ipa文件啊。。不然完全不知道怎么安装啊。。哪位好心人救救我啊

**Comment by DaidoujiChen** [comment]
https://github.com/DaidoujiChen/Dai-Hentai/issues/167

**Comment by 302766440** [comment]
> #167

那个链接打不开啊作者大大。。没法下载。。可以麻烦重新上传吗。。求求
