### ISSUE TITLE
搜索关键词后列表会一直重复显示前几本

### ISSUE THREAD

**Issue by k2rr** [DaidoujiChen/Dai-Hentai#169]
如题，不知道和ios16有没有关系，最近搜索关键词后列表会一直重复显示前几本，往下翻都是重复的几本。OS：16.1  model：iphone13promax

**Comment by DaidoujiChen** [comment]
應該是 ex 的分頁方式改變惹
這個應該有修惹鷗

**Comment by k2rr** [comment]
抱歉~ 拉取最新的build安装后正常了，打扰啦，感谢
