### ISSUE TITLE
请问是否有方法可以迁移下载的漫画？

### ISSUE THREAD

**Issue by 302766440** [DaidoujiChen/Dai-Hentai#170]
我的一台手机装的是3.10版本，能否把里面已下载的漫画迁移到另一台手机（最新的3.11版本）

**Comment by DaidoujiChen** [comment]
Hello @302766440,

這個我不確定的說
因為我已經很久沒有可以換新的裝置惹
QwQ

**Comment by k2rr** [comment]
设备越狱了的话直接把Documents和Library直接覆盖过去就可以了，单独拖Documents的话应该列表看不见

**Comment by white7saber** [comment]
> 我的一台手机装的是3.10版本，能否把里面已下载的漫画迁移到另一台手机（最新的3.11版本）

你有3.11的ipa文件吗，不会打包o.o

**Comment by k2rr** [comment]
> > 我的一台手机装的是3.10版本，能否把里面已下载的漫画迁移到另一台手机（最新的3.11版本）
> 
> 你有3.11的ipa文件吗，不会打包o.o
参考readme里的最新测试ipa章节，已经可以获取到ipa了。记得前段时间还不能用，应该是作者维护了，赞美。

**Comment by DaidoujiChen** [comment]
包好的 3.11 在這邊

https://s3-ap-northeast-1.amazonaws.com/dai-hentai-ipa/bitrise/3.11_20221117/Dai-Hentai.ipa

**Comment by white7saber** [comment]
感谢，解决了

**Comment by DaidoujiChen** [comment]
OwOb
