### ISSUE TITLE
请问升级新版本，是否会抹掉原来已下载的漫画？

### ISSUE THREAD

**Issue by 302766440** [DaidoujiChen/Dai-Hentai#171]
我的手机已经越狱，装的app是3.10版本，现在要升级3.11版本，如果直接导入ipa安装，是否会把我原来已下载的漫画都清空了呢

**Comment by DaidoujiChen** [comment]
Hello @302766440,

直接從 3.10 -> 3.11 的話 裡面既有的資料不會改變
