### ISSUE TITLE
下載的太快也是個問題.....

### ISSUE THREAD

**Issue by DaidoujiChen** [DaidoujiChen/Dai-Hentai#19]
要開一個選項出來讓使用者把速度調低...

**Comment by DaidoujiChen** [comment]
後來我檢查了一下, 在直接看裡面一次最多開 5 個頁面, 而下載兩本同時跑的話總共也只有 4 個頁面, 合計起來是 9 個而已, 在想是不是有其他的原因?

**Comment by carry0987** [comment]
我倒覺得下載太慢.....

**Comment by DaidoujiChen** [comment]
@carry0987,

O口O"

**Comment by carry0987** [comment]
大大，ios 8.3 不能載Dai Hentai 了

DaidoujiChen <notifications@github.com> 於 2015年6月21日 星期日寫道：

**Comment by DaidoujiChen** [comment]
Hello @carry0987,

其實不是 8.3 的問題, 如果你說的是直接下載安裝的話, 浦公英的憑證很早以前已經被 apple 殺光光了,
所以沒有辦法讓大家像之前這樣裝, 但是 ios9 會有一線曙光, 可以等等看, 謝謝.

**Comment by carry0987** [comment]
呃，現在又可以了.....

DaidoujiChen <notifications@github.com> 於 2015年6月26日 上午10:12 寫道：

**Comment by DaidoujiChen** [comment]
@carry0987 

也太神祕了 O3O

**Comment by carry0987** [comment]
對了，可以用ipa版的嗎?或是安裝檔?因為手機下載很慢...

2015-06-26 17:47 GMT+08:00 DaidoujiChen <notifications@github.com>:

**Comment by carry0987** [comment]
大大哈囉??

鄭成功 <carry0987@gmail.com> 於 2015年6月26日 下午6:28 寫道：

**Comment by DaidoujiChen** [comment]
Hello @carry0987,

可以在 https://github.com/DaidoujiChen/Dai-Hentai/releases 這邊直接下載 ipa 檔案, 不過如果沒有 jb 的話, 應該是沒有辦法使用才對.

**Comment by carry0987** [comment]
已JB,謝謝大大！

DaidoujiChen <notifications@github.com> 於 2015年6月27日 星期六寫道：

**Comment by DaidoujiChen** [comment]
因為後來這些留言已經偏離主題了, 晚一些我會刪除掉一些.

**Comment by carry0987** [comment]
好！

DaidoujiChen <notifications@github.com> 於 2015年6月27日 星期六寫道：

**Comment by carry0987** [comment]
大大，2.5好像會當掉？我試過ios 8.1.2 & ios 8.3 了，都會當掉

鄭成功 <carry0987@gmail.com> 於 2015年6月27日 星期六寫道：
