### ISSUE TITLE
e-hentai 的 api 掛掉了

### ISSUE THREAD

**Issue by DaidoujiChen** [DaidoujiChen/Dai-Hentai#2]
不知道這是常態現象還是臨時問題, 剛剛要測的時候發現掛了, 導致 load 不出作品的相關資訊.

**Comment by DaidoujiChen** [comment]
到目前看起來都運作正常

**Comment by DaidoujiChen** [comment]
API 一直回

`````
{
  "error": "Empty JSON Request"
}
`````

**Comment by DaidoujiChen** [comment]
奇妙的是 ex 居然行..... =_____=

**Comment by carry0987** [comment]
我也發現這個奇妙的事~

2017-01-29 21:20 GMT+08:00 DaidoujiChen <notifications@github.com>:

**Comment by carry0987** [comment]
EX比eh還要龐大ㄟ

2017-01-29 22:41 GMT+08:00 鄭成功 <carry0987@gmail.com>:

**Comment by DaidoujiChen** [comment]
網址都調整為 https 的囉
