### ISSUE TITLE
增進下載管理器的功能

### ISSUE THREAD

**Issue by DaidoujiChen** [DaidoujiChen/Dai-Hentai#28]
比方說要可以刪除正在下載的部分, 或是移動順序之類的.

**Comment by DaidoujiChen** [comment]
這一塊要好好規劃一下了, 記錄下載狀況, 閃退時的 recovery 之類的.

**Comment by ipfans** [comment]
好像并么有看到正在下载功能？

**Comment by DaidoujiChen** [comment]
Hello @ipfans,

左邊滑開是功能列表
右邊滑開是下載清單

**Comment by DunkMaster** [comment]
請問怎樣刪除已下載的漫畫

**Comment by DaidoujiChen** [comment]
在觀看作品的右上角喔

或者是因為 https://github.com/DaidoujiChen/Dai-Hentai/commit/f4a452e0d777b8b575d9f34586f613e05835425a 導致那個版本的直向觀看的刪除鈕不見了

**Comment by DaidoujiChen** [comment]
在 https://github.com/DaidoujiChen/Dai-Hentai/commit/0d26f96d6dc8a1156ca1bdc2abee50ecc69a1e31 裡面, 加入利用 gps 的方式, 讓下載可以延續
