### ISSUE TITLE
直接在线阅读时，无法利用之前在线阅读后的缓存

### ISSUE THREAD

**Issue by anamewing** [DaidoujiChen/Dai-Hentai#38]
缓存映射中使用的key是下载路径中最后两段。
但每次重新打开同一个漫画时，获得的倒数第二段路径中的两个数字字符串都会有所不同。这导致无法在映射表中查询到之前下载过的图。

**Comment by DaidoujiChen** [comment]
Hello @anamewing,

耶? 真的嗎? 因為那個 key 應該是絕對的說
以同一部作品來說
網址是 `http://g.e-hentai.org/g/838693/c7cc5ee27d/` 的時候
後面兩段的 `838693` 跟 `c7cc5ee27d` 應該是不會變的吧 O3O?

我們說的是同一個地方嗎?

**Comment by anamewing** [comment]
`hentaiKey` 确实是唯一的，但是对于在漫画每张图显示的时候，用的是类似 `hentaiResults[[eachImageString hentai_lastTwoPathComponent]]` 这样的方法，我指的是 `hentai_lastTwoPathComponent` 这里选择了最后两段路径。

我试了几次，图片在缓存服务器上保存的方式见到了两种
```
* http://220.132.182.196:20845/h/dfa7ed39f7869b036487700deac761d821404351-207119-1200-1719-jpg/keystamp=1438583700-fe349d1119/001.jpg
* http://37.48.81.90/ehg/image.php?f=fe58d76d5463006c2e99fb9738c1e304b1a10536-75921-1200-1695-jpg&t=399606-a3d9a57e693951e56034817dc36a8a779805d4cb&n=038.jpg
```

对于第一种情况，倒数第二段中的 `1438583700` 和 `fe349d1119` 都是每次连接会变的；对于第二种情况，恐怕需要使用&做分隔符了。不过第二种情况蛮少见的。

**Comment by DaidoujiChen** [comment]
Hello @anamewing,

喔喔, 對, 那個地方會變, 包括從不同的地區(VPN)去讀取同一個網頁的時候,
有時候回的圖片位置都會不太一樣

這邊我沒有想到一個最佳的方法來避免這個問題
最一開始我們的做法是只拆最後一個部分
像是 `001.jpg`, `038.jpg`
不過在某些神奇的本子裡面
他會有比如說第一頁跟第二十頁都叫 `001.jpg` 的情況
所以才把這個判斷加嚴, 讓他連前面的段落都切進去當作判斷的依據
O3O

**Comment by anamewing** [comment]
在这个时候， `hentaiResults` 中存储的各个元素的key就会是 `keystamp=1438583700-fe349d1119-001.jpg` 这种名字，因此第二次打开时不会命中缓存。

**Comment by DaidoujiChen** [comment]
@anamewing 
嗯嗯 我懂 O3O

**Comment by DaidoujiChen** [comment]
@anamewing 

這邊我後來有個想法, 找時間我會看一下 code 看可不可行
O3O
