### ISSUE TITLE
是否可以让直接在线阅读时也支持“水平滚动浏览”

### ISSUE THREAD

**Issue by anamewing** [DaidoujiChen/Dai-Hentai#39]
现在应用中只允许已下载的漫画水平滚动浏览，不知具体的原因？

**Comment by DaidoujiChen** [comment]
Hello @anamewing,

這個比較好回, 我先回這一個, 應該是因為使用套件的關係,
直向滾動的瀏覽方式是我自己寫的,
水平滾動則是第三方的, O3O

我有點忘了
不確定是不是不能直接讀取線上的圖片還是怎麼樣的
這個部分可能要再查查.

**Comment by anamewing** [comment]
那么……图片下载也交给自己来做，只是让第三方的库来显示图片呢？

**Comment by DaidoujiChen** [comment]
Hello @anamewing,

圖片下載的部分是我整個用手寫的, O3O
所以沒有用第三方的東西,
點直接看的時候, 其實大家也都還不知道網址,
所以我自己的做法是可以等到圖片來了, 再把資料回填

但是第三方的那個套件好像不行
必須準備好一串要顯示的圖片 array 給他
要改應該也不是不行
需要花時間去看一下就是了 O3O
