### ISSUE TITLE
不启用定位的话，app会卡死

### ISSUE THREAD

**Issue by ayconanw** [DaidoujiChen/Dai-Hentai#40]
定位功能是必须的吗？
因为平时手机电量比较不够，一般在系统设置里把整个定位功能给关掉的

**Comment by DaidoujiChen** [comment]
Hello @ayconanw,

我找時間看看, 但是一般來說這個 app gps 也不會一直開起來,
只會在 `正在下載漫畫` + `app 被退到背景` 這兩個同時成立的時候
gps 會被開啟, 然後好像大概 100 還幾秒會啟動一次, 維持到漫畫都抓完後就關閉,
理論上啦, 應該是不會太吃電.

**Comment by ayconanw** [comment]
@DaidoujiChen 我明白定位是为了后台下载，也清楚这个不会太耗电。
只是我平时是把定位功能整体关掉的（在 系统设置-隐私 里禁用了整个系统的定位功能），特别是在ipad上，定位基本没有机会用到。我感觉这么做的大概也不止我一个人，应该能代表一部分用户的习惯。
只是希望daihentai不要强制要求定位功能，不开定位时候不给下载也可以，能在线看就好。像google maps这种特别需要定位的app，不开定位也是可以进去查看地图的，只是缺失了导航等功能。

**Comment by DaidoujiChen** [comment]
Hello @ayconanw,

好, 我了解了, 我會再試試這個部分, 謝謝囉.

**Comment by DaidoujiChen** [comment]
Hello @ayconanw,

我可以重現這個問題, 不過還正在找 root cause.

**Comment by DaidoujiChen** [comment]
主要的原因是因為其實會跳一個確認 gps 打開的 alertview, 不過因為他太快出現的, 快到被壓在主畫面下,
所以無法對這個 alertview 進行選擇操作, 主畫面也被 alertview 的出現限制住行為
