### ISSUE TITLE
你好 请问新版本去哪里能下载？

### ISSUE THREAD

**Issue by a8778700** [DaidoujiChen/Dai-Hentai#42]

**Comment by DaidoujiChen** [comment]
Hello @a8778700,

目前只有兩個方法可以安裝,
1. 你有 mac 電腦, 可以把源碼 build 到自己的手機或是平板上面.
2. 你有 jb, 可以把 ipa 直接丟到手機或是平板上面.
最新的版本都可以從
https://github.com/DaidoujiChen/Dai-Hentai/releases/tag/v2.6 找到
除此之外, 目前我也還沒有想到其他方法.
