### ISSUE TITLE
请问可以推到pgyer上么？

### ISSUE THREAD

**Issue by chintj** [DaidoujiChen/Dai-Hentai#43]
请问可以推到pgyer上么？
求企业证书支持

**Comment by DaidoujiChen** [comment]
Hello @chintj,

最之前就是放在浦公英上耶, 不過後來浦公英的證書死光光, 好像就沒有辦法用了,
必須要自己企業簽章才行, O3O, 但是那個東西除了貴, 一般人也不是那麼容易申請,
所以就一直沒有在弄.

**Comment by CaiMiao** [comment]
那能否host并分发ipa package？方便jb用户，蒲公英现在的可以装但是用不了。

**Comment by DaidoujiChen** [comment]
Hello @CaiMiao,

因為沒有 jb 過, 所以不知道該怎麼弄到 host 上說, O口O"

**Comment by CaiMiao** [comment]
编译之后建个release，把ipa扔到里面。github好像允许host可执行档案的。

**Comment by DaidoujiChen** [comment]
Hello @CaiMiao,

在 https://github.com/DaidoujiChen/Dai-Hentai/releases 是有 build 完成的 ipa 檔案, O3O

**Comment by CaiMiao** [comment]
我..没看到(⁄ ⁄•⁄ω⁄•⁄ ⁄)

发自我的 iPhone

**Comment by DaidoujiChen** [comment]
:+1:

**Comment by CaiMiao** [comment]
还是不能用，登录后封面空白，页数信息等等都是null

**Comment by DaidoujiChen** [comment]
Hello @CaiMiao,

可能需要翻牆才行喔, O3O

**Comment by CaiMiao** [comment]
这是什么原理。。。国内可以无墙正常访问ex的啊(web)。。。求开发国内模式

**Comment by DaidoujiChen** [comment]
Hello @CaiMiao,

這個我就不太清楚了說, O3O, 一直沒有去弄往牆內跳的 vpn 來做這個測試

**Comment by CaiMiao** [comment]
有一定的几率可以刷出来(表)很小

**Comment by CaiMiao** [comment]
测试了，墙内获取的list不正确，虽然可以看但是名字封面都是空白，不能抓
翻墙获取正确list之后回墙可以看也可以抓

**Comment by CaiMiao** [comment]
https://www.flyvpn.com/cn/freetrial
试试这个...‹‹\( ˙▿˙ )/››

**Comment by DaidoujiChen** [comment]
Hello @CaiMiao,

喔喔!! 好, 我會再試試看, O3Ob

**Comment by CaiMiao** [comment]
Personal comments moved to #44.
