### ISSUE TITLE
cai_miao的issue回报帖以及enhancement意见

### ISSUE THREAD

**Issue by CaiMiao** [DaidoujiChen/Dai-Hentai#44]
Issue:
- 进场图没有了ᕙ(⇀‸↼‵‵)ᕗ

Enhancement:
- 在阅读时底部读取时加入loading icon并显示实时速度 (在什么地方显示一个global实时速度也不错)
- 增进「取消加载」「默认进场区」(自选进场入e、ex、下载区)「无网自动进下载区(无视进场区设定)」「一时间忘记了，想到什么再补吧」

**Comment by CaiMiao** [comment]
Report 大陆仍然无法load到list，起因不明

**Comment by CaiMiao** [comment]
怪了，，，挂v都login不到，不知道出了什么毛病

**Comment by DaidoujiChen** [comment]
Hello @CaiMiao,

是說沒有辦法登入 ex 嗎?
最近我在寫另一隻 app 的時候發現
好像 ex 最近沒有辦法正常的登入
包括使用網頁登入都是
他會需要輸入一個驗證碼才行
不知道是不是異常才會這樣

**Comment by CaiMiao** [comment]
应该就是这个情况的呢

**Comment by DaidoujiChen** [comment]
:)

**Comment by CaiMiao** [comment]
Comment updated!

**Comment by DaidoujiChen** [comment]
O3O?

**Comment by CaiMiao** [comment]
看最上面啦

**Comment by DaidoujiChen** [comment]
哈哈 好

**Comment by DaidoujiChen** [comment]
可以私信給我你常用的信箱嗎 O3O
daidoujichen@gmail.com
感恩

**Comment by zhangyubaka** [comment]
仍然无法登陆 ex 呢...

**Comment by DaidoujiChen** [comment]
Hello @zhangyubaka,

我找時間再試一下.

**Comment by zhangyubaka** [comment]
嗯嗯
DaidoujiChen <notifications@github.com>于2016年10月4日 周二上午8:23写道：

**Comment by DaidoujiChen** [comment]
@zhangyubaka,

好像真沒辦法 O口O"
