### ISSUE TITLE
Exhentai讀取使用e-hentai的Api.php

### ISSUE THREAD

**Issue by wangtao03** [DaidoujiChen/Dai-Hentai#46]
Exhentai主頁讀取仍使用e-hentai.org/api.php獲取相關Json

**Comment by CaiMiao** [comment]
这是大陆无法get正确列表的主因？

**Comment by DaidoujiChen** [comment]
Hello @wangtao03,

是的, 因為 ex 的資料只是在 e 看不見, 但是從 api 去打的話, 是可以找到 ex 的作品的.

**Comment by DaidoujiChen** [comment]
Hello @CaiMiao,

有可能喔!

**Comment by DaidoujiChen** [comment]
@CaiMiao 

在不翻牆的情況下, 如果你直接打 `http://e-hentai.org/api.php` 這個網址的話, 會有什麼結果呢?
我這邊的話會是

![2016-01-28 10 03 23](https://cloud.githubusercontent.com/assets/670441/12646428/004385b0-c60b-11e5-8c95-1bf7650e8f9f.png)

**Comment by CaiMiao** [comment]
一样是not found呢

**Comment by carry0987** [comment]
在Documents
資料夾裡面有個叫做「HentaiSaveLibrary」的檔案，裡面有加密過(不確定，因為打開有亂碼)，裡面有下載過的檔案的ID,我之前只備份Documents
的資料夾，沒有把這個檔案裡面的內容也一併複製，所以才造成覆蓋了整個Documents 資料夾卻沒有顯示任何一本的狀況。

P.s. 主要只是詢問能不能自己編輯HentaiSaveLibrary的內容，讓資料轉移方便一點....
還請大大過目

**Comment by DaidoujiChen** [comment]
Hello @carry0987,

明天我看一下, O3O

**Comment by carry0987** [comment]
謝謝你～

DaidoujiChen <notifications@github.com> 於 2016年2月14日 星期日寫道：

**Comment by CaiMiao** [comment]
建议采取API可选择制，雷同于Android上绅士道的工作方式，任君选择。

**Comment by CaiMiao** [comment]
、

**Comment by carry0987** [comment]
現在就等作者明天的決定咯～

CaiMiao <notifications@github.com> 於 2016年2月15日 星期一寫道：

**Comment by DaidoujiChen** [comment]
Hello @carry0987, @CaiMiao,

可以麻煩你們用常用的信箱寄信給我嗎?
謝謝 O3O
daidoujichen@gmail.com

**Comment by DaidoujiChen** [comment]
Hello @carry0987 , @CaiMiao,

請問 [lofi](http://lofi.e-hentai.org/?f_doujinshi=1&f_manga=1&f_artistcg=1&f_gamecg=1&f_western=1&f_non-h=1&f_imageset=1&f_cosplay=1&f_asianporn=1&f_misc=1&f_search=%E9%A4%98%E7%AD%86&f_apply=Apply+Filter) 這個網站有被牆嗎?

我用 [checkgfw](http://www.checkgfw.com/) 說有, 但是我記得好像之前很多人說這個可以看?
謝謝.

**Comment by CaiMiao** [comment]
部分地区会墙，是不同的运营商/电信业者决定的

**Comment by DaidoujiChen** [comment]
:+1:

**Comment by ctsgh** [comment]
已知架设在digital ocean上的翻墙shadowsocks vps不可看eh

**Comment by DaidoujiChen** [comment]
其實我架過一台 aws vpn 的主機放在東京
用那台 vpn 也沒有辦法看 eh
原因不明

**Comment by ctsgh** [comment]
可能是故意挡住不让人跑H@H，免得万一出问题波及其他vps
