### ISSUE TITLE
无法完整阅读问题和信息显示Null问题

### ISSUE THREAD

**Issue by xxf1995** [DaidoujiChen/Dai-Hentai#49]
最近只能阅读每本的前40页，后面的无论如何都加载不出来。还有个问题是有关书的一切信息都显示Null。因为最近在大陆，使用了香港的Shadowsocks代理阅读；是导致问题的原因吗？

**Comment by DaidoujiChen** [comment]
Hello @xxf1995,

我試試.

**Comment by DaidoujiChen** [comment]
Hello @xxf1995,

可能是牆內的問題, 我這邊大概試了一下, 第一個圖是 95/95/95, 所以應該是可以完整的讀取完整本作品,
<img width="432" alt="2016-09-04 9 55 25" src="https://cloud.githubusercontent.com/assets/670441/18231359/7661af4c-72ea-11e6-9caa-6d3ee41fbfa0.png">

第二個圖是列表的部分, 正常應該是, 沒有 NULL 字樣顯示的問題
<img width="432" alt="2016-09-04 9 56 02" src="https://cloud.githubusercontent.com/assets/670441/18231364/c644cd96-72ea-11e6-921e-4789b505557f.png">

**Comment by xxf1995** [comment]
是的。。伟大的墙。。回States就好了

**Comment by DaidoujiChen** [comment]
那我就把他 close 掉囉
感恩
