### ISSUE TITLE
iPhone版点击搜寻的评价限制时会crash

### ISSUE THREAD

**Issue by Cxh012** [DaidoujiChen/Dai-Hentai#52]
![cd684c72-ed21-4bb4-a635-9b7ea763dcf2](https://cloud.githubusercontent.com/assets/15240481/19188294/74d31470-8cc3-11e6-8339-597c257deaa6.png)
定位到这一行

**Comment by DaidoujiChen** [comment]
Hello @Cxh012,

Q口Q"
好.....我看...

**Comment by DaidoujiChen** [comment]
原專案 QuickDialog 有被發現這個 issue
修正參考 [PR](https://github.com/escoz/QuickDialog/pull/720/files)
