### ISSUE TITLE
请问ehentai账号无法登陆怎么办？

### ISSUE THREAD

**Issue by yhc1994** [DaidoujiChen/Dai-Hentai#53]
无论使用4G还是WIFI，点击exhentai输入用户名和密码登陆之后就一直loading了，没有任何反应
好像安卓端的ehviewer今年上半年的时候也不能登陆，后来使用网页登陆验证后就好了（网页登陆可以显示验证码），大大有更新计划吗
另我看上面说1.4版本之后就有app icon了可是在我的iphone里还是白白的

**Comment by DaidoujiChen** [comment]
Hello @yhc1994,

 * ex 的問題如果要改的話, 可能會花稍微長一些的時間, 我在另外一個專案裡面有用另種登入的方法,
我再找時間把他搬過來試試看.

 * icon 應該會有的說, 請問你的裝置是什麼呢?

感恩

**Comment by yhc1994** [comment]
手机是iphone7plus，系统是10.0.2，试着重装了好几次都没有app icon

**Comment by yhc1994** [comment]
还有个小问题就是在我的手机上，点击搜索，再点击评价限制那一项之后app会100%几率闪退

**Comment by DaidoujiChen** [comment]
Hello @yhc1994,

會 crash 的那個問題, 這幾天已經修掉囉 https://github.com/DaidoujiChen/Dai-Hentai/issues/52

你是抓 ipa 裝的還是自己用 xcode build 到 iphone7plus 裡面的 O3O?

**Comment by yhc1994** [comment]
ios还不能jb所以只能自己build到iphone，软件版本是2.62

**Comment by DaidoujiChen** [comment]
喔喔 因為 github 上面的專案沒有上圖 所以就會沒有 icon >w<" 這是正常的

**Comment by kayanouriko** [comment]
@DaidoujiChen 请问一下你的另一种登陆方式实现是怎么样的,能告诉我在哪我参考一下么,我对与ios模拟网页表单提交这一块不是很熟悉...想看看多样的实现方式

**Comment by DaidoujiChen** [comment]
Hello @kayanouriko,

https://github.com/DaidoujiChen/Shinsi

這本來是我 fork 的一個項目
原來的主人好像刪除掉他自己的了
確切的代碼在這一塊

https://github.com/DaidoujiChen/Shinsi/blob/master/Shinsi/RequestManager.swift#L181-L197

這裡面的做法比當前這個項目的方法高明

我在我另外一個 swift 的項目裡面有實作
會把他轉成 objc 的版本搬過來

你可以先參考看看

**Comment by kayanouriko** [comment]
@DaidoujiChen 回复晚了感到抱歉,十分感谢你的回答并提供链接...=3=
确实该项目中登陆判断是通过截图网页标题来进行的,感觉上并非一个很好的通用解决方案...
swift还没进行过系统的学习,估计我自己看起来够呛;w;
我先自己琢磨一下吧.
再次感谢作者大大=3=

**Comment by DaidoujiChen** [comment]
Hello @kayanouriko,

新的實作方式在
https://github.com/DaidoujiChen/Dai-Hentai/pull/61

會持續的再試一下再 merge 回 master

**Comment by Cxh012** [comment]
@DaidoujiChen 發現iOS10下使用UIWebView會丟這個錯誤：
WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
猜測是iOS10出現了AD BLOCK插件

**Comment by DaidoujiChen** [comment]
Hello @Cxh012,

你可以試一下正在 pr 中的那條 branch 嗎?
那個做法就完全沒有用到 webview 囉
感恩

**Comment by Cxh012** [comment]
@DaidoujiChen 
那個branch我跑起來發現完全登錄不上去的樣子…orz

**Comment by DaidoujiChen** [comment]
@Cxh012 

O口O"

**Comment by JohnisaSB** [comment]
同样用正在pr的branch跑了一遍，也是无法登陆e-hentai账号，iOS 10.0.2

**Comment by DaidoujiChen** [comment]
@JohnisaSB 
好的.....謝謝...

**Comment by DaidoujiChen** [comment]
未來的版本應該會有解囉

https://github.com/DaidoujiChen/Dai-Hentai/pull/61
