### ISSUE TITLE
xcode上编译报ld: library not found for -lChameleonFramework

### ISSUE THREAD

**Issue by caunion** [DaidoujiChen/Dai-Hentai#55]
版本：2.62 release
只修改了bundle identifier 和 team，直接编译报错。
本地xcode是最新的，mac osx 10.11。我看了一下Chemelon在pod里面有，是不是编译的时候要在什么地方指定编译顺序和搜索路径？

**Comment by caunion** [comment]
已解决。
应该打开.xcworkspace文件。

**Comment by DaidoujiChen** [comment]
@caunion ya
那我關掉囉

**Comment by caunion** [comment]
ok ，谢谢：）
btw，如果可以，希望能够在readme里面提一下这一点。
我之前没用过xcode编译所以搞错。我猜想可能也会有别的用户不清楚这一点。：）

**Comment by DaidoujiChen** [comment]
已加入 commit https://github.com/DaidoujiChen/Dai-Hentai/commit/ed77f6c21033bbce361ff08b83e9e966781e99a4
