### ISSUE TITLE
于GitHub上託管的專案似乎存在無法編譯的問題

### ISSUE THREAD

**Issue by Cxh012** [DaidoujiChen/Dai-Hentai#56]
我嘗試重新下載完整的Zip檔案解凍后使用xcworkspace打開，出現下圖狀況。
![2](https://cloud.githubusercontent.com/assets/15240481/20629633/96fa8fd6-b367-11e6-96b3-2bc3586ac9fe.png)
![1](https://cloud.githubusercontent.com/assets/15240481/20629634/96ff5200-b367-11e6-9bc0-de1500847a81.png)

同時，坐標澳門，出現了EXHENTAI預覽圖無法加載的狀況。

**Comment by DaidoujiChen** [comment]
Hello @Cxh012,

前幾天我本來想整理一下項目
也有無法編譯的問題
這兩天應該會看一下是怎麼樣了
因為都沒有動
放著就壞了
可能跟 xcode 改版或是一些 third party 的東西需要更新有關

**Comment by DaidoujiChen** [comment]
Hello @Cxh012,

我有調整一些地方了, 然後我的 xcode 版本是

![2016-11-26 8 32 57](https://cloud.githubusercontent.com/assets/670441/20640388/8a05c722-b417-11e6-9c27-18cd8f379409.png)

可以正常編譯, 再麻煩試試看, 感恩

**Comment by Cxh012** [comment]
似乎還是無法編譯的樣子？你有沒有試過直接從git上面clone整個專案編譯呢？

**Comment by Cxh012** [comment]
clean过后将Always Search User Paths 设为YES ，即可解决

**Comment by DaidoujiChen** [comment]
我試一下喔! 我記得之前好像有回過類似的問題 (?

**Comment by DaidoujiChen** [comment]
然後我用 clone 的方式下載回我的電腦
解壓之後還是可以正常編譯
剛剛我到回過的問題是這一個

https://github.com/DaidoujiChen/Dai-Hentai/issues/48

但是看起來感覺跟你遇上的不太一樣

**Comment by Cxh012** [comment]
重做了系统之后解决了:D
