### ISSUE TITLE
新的版本

### ISSUE THREAD

**Issue by hpigu** [DaidoujiChen/Dai-Hentai#58]
請問能不能發一個新的版本，目前的版本ex紳士無法顯示圖片

**Comment by DaidoujiChen** [comment]
O3O
這兩天我找時間弄一下

**Comment by hpigu** [comment]
謝謝大大

**Comment by DaidoujiChen** [comment]
[版本 2.63](https://github.com/DaidoujiChen/Dai-Hentai/releases/tag/2.63)
