### ISSUE TITLE
在Windows/Linux下安裝Dai-Hentai的方式

### ISSUE THREAD

**Issue by codexss** [DaidoujiChen/Dai-Hentai#64]
下載ipa文件https://github.com/DaidoujiChen/Dai-Hentai/releases
下載Cydia Impactor http://www.cydiaimpactor.com
插上iPhone打開Cydia Impactor將ipa拖放進Cydia Impactor軟件裡，登上你的蘋果id(安全性待考證)，點擊開始，等待你的手機出現Dai-Hentai吧！
![](https://cloud.githubusercontent.com/assets/5959201/21889171/82c62cc6-d902-11e6-82f9-c86a2a0645ca.png)

**注意，這個安裝方式只能使用軟件七天，七天后軟件就會消失**

![](https://cloud.githubusercontent.com/assets/5959201/21889218/d148a7fc-d902-11e6-8a3d-178721f89ed4.png)

**Comment by codexss** [comment]
可以考虑写入readme.md @DaidoujiChen

**Comment by DaidoujiChen** [comment]
@codexss 
好妙 這要 jb 嗎?

**Comment by codexss** [comment]
不需要jb，但是需要每七天重装一次

DaidoujiChen <notifications@github.com>于2017年1月12日 周四22:46写道：

**Comment by DaidoujiChen** [comment]
>w<
感謝
我再把他加進去

**Comment by codexss** [comment]
另外在我iPhone7上显示有点错位

DaidoujiChen <notifications@github.com>于2017年1月12日 周四22:51写道：

**Comment by DaidoujiChen** [comment]
@codexss 
可以麻煩也幫我截一張圖嗎
如果問題比較小的話我有時間可以修
謝謝

**Comment by codexss** [comment]
截什么图？上面已经发了⸜( ˙-˙ )⸝
DaidoujiChen <notifications@github.com>于2017年1月12日 周四23:10写道：

**Comment by codexss** [comment]
email回复的图片貌似没过来，补一张，左边的菜单文字显示宽度不够……
![image](https://cloud.githubusercontent.com/assets/5959201/21897845/b8742a6c-d925-11e6-98f8-3c764573701d.png)

**Comment by DaidoujiChen** [comment]
喔喔
那好像是本來就不夠的 >w<"
是寫一個固定的寬度而已

**Comment by codexss** [comment]
看看能不能弄成动百分比的宽度，或者弄成弹出菜单，缺一块感觉怪怪的

**Comment by codexss** [comment]
另外希望加入收藏功能
