### ISSUE TITLE
为什么储存漫画后要回到目录？

### ISSUE THREAD

**Issue by hkalexling** [DaidoujiChen/Dai-Hentai#66]
即，`PhotoViewController.m` 中的 `saveAction`完成后为什么要 call `[self backAction]`?

个人使用时会先搜索，找到合适的漫画后选择「直接看」，看了一部分觉得喜欢就会选择储存漫画。这时候虽然加入下载了还是想继续看下去的，但却被强行退回到目录，感觉体验上有点不好。

这一点能否改进一下，或者至少允许用户自行设置储存后的行为呢？(大大同意的话在下可以提 PR~)

**Comment by DaidoujiChen** [comment]
O3O
我忘了 我要想一下為什麼

**Comment by DaidoujiChen** [comment]
@hkalexling 

好像是因為儲存機制的問題
當初沒有設計的很好
我不知道好不好改的說
你可以先發一版看看
然後我們把他改好 O3Ob
感恩

**Comment by hkalexling** [comment]
感谢回复~

在下稍微看了下没有发现为什么会不好改？应该只是去掉[这一行](https://github.com/DaidoujiChen/Dai-Hentai/blob/master/e-Hentai/PhotoViewController/PhotoViewController.m#L88)的事情呀？实际测试了也没有问题。还是说大大说的是要在设定中添加这个选项？

**Comment by DaidoujiChen** [comment]
喔喔!
明天我會花點時間來看一下 跟回憶一下
感恩

**Comment by DaidoujiChen** [comment]
大概看過一下
因為當初設計

`````
短暫使用(直接看)的漫畫會存放到 Cache 資料夾下
長期使用(儲存)的漫畫會放到 Document 資料夾下
`````

會這樣設計當初是想說把 `直接看` 所有的本本都集中到同一個資料夾下的時候, 方便計算容量也好砍.

所以在使用者選擇 `加入下載管理員` 的時候, app 會做的行為是

1. 加入下載 Queue [[HentaiDownloadCenter addBook:self.hentaiInfo toGroup:selectedGroup];](https://github.com/DaidoujiChen/Dai-Hentai/blob/master/e-Hentai/PhotoViewController/PhotoViewController.m#L87)
2. 強制使用者退出正在看的漫畫 [[self backAction];](https://github.com/DaidoujiChen/Dai-Hentai/blob/master/e-Hentai/PhotoViewController/PhotoViewController.m#L88)
3. 當下載任務結束的時候, 為了確保容量沒有被浪費, 所以會回過頭砍掉 `Cache` 資料夾裡面的同一本漫畫

所以不退出, 讓使用者還繼續看的話, 會有兩種可能
1. 看到一半就讀取不到圖片了, 因為圖片已經被下載任務刪除
2. 下載任務已經刪除過, 正在看又新增加圖片到 `Cache` 資料夾, 導致容量佔用變多

總言之, o.o
這是當初儲存機制設計不良造就的因.....
我來想一下是不是對他做什麼調整
感恩
