### ISSUE TITLE
搜索时选择评价限制会闪退

### ISSUE THREAD

**Issue by zhangyubaka** [DaidoujiChen/Dai-Hentai#67]
master , iOS 10.2

**Comment by DaidoujiChen** [comment]
>w<" 我先解個隔壁棚的 bug

**Comment by zhangyubaka** [comment]
感恩 /

**Comment by DaidoujiChen** [comment]
Hello @zhangyubaka,

我試了一下, 我這邊的版本好像 ok 的說,
請問使用最新的版本嗎?
因為過去有一個 issue 也是類似的問題

https://github.com/DaidoujiChen/Dai-Hentai/issues/52

參考一下是不是一樣的事情
感恩 >w<

**Comment by zhangyubaka** [comment]
切换到了正在 pr 的版本， 依旧闪退 O.O
![image](https://cloud.githubusercontent.com/assets/7823161/22184124/bebf9ef4-e106-11e6-834b-826ec35e059d.png)
Xcode 定位到这里

**Comment by DaidoujiChen** [comment]
喔喔 我可能猜到是為什麼了 我試一下

**Comment by DaidoujiChen** [comment]
後來某一次改版, cocoapods 內的東西變成每個人要重新拉過, 所以導致如果拉的是對方項目原來的版本,
可能就會有問題, O口O", 因為有些東西我有修改過, 我再想想這部分要怎麼解決, 感恩

**Comment by zhangyubaka** [comment]
下载管理中选择分类 => 从旧有分类选择会 crash.
![image](https://cloud.githubusercontent.com/assets/7823161/22336682/fde8dd2e-e41d-11e6-9b87-06bad8d31e98.png)

**Comment by DaidoujiChen** [comment]
好呦
新年快樂
我有時間會再試試
感恩

**Comment by bulunihaha** [comment]
作者大
根據你的指示#52 
確定是可行的
-----------------------
下載管理分類那個
好像是很老舊有的bug了
我都是直接輸入分類名稱，這樣就不會有問題了

**Comment by DaidoujiChen** [comment]
3q @bulunihaha

**Comment by zhangyubaka** [comment]
顺道问一下...怎么删除已下载的文件呢 Q.Q

**Comment by DaidoujiChen** [comment]
O3O? 已經下載是什麼意思
應該在橫向或是直向的觀看頁面
右上角都有刪除的按鈕可以按喔

**Comment by zhangyubaka** [comment]
如果选择横向观看的话是没有删除按钮的..

DaidoujiChen <notifications@github.com>于2017年1月30日周一 上午12:54写道：

**Comment by DaidoujiChen** [comment]
喔喔 這跟前面的問題是一樣的
因為 pod `MWPhotoBrowser` 有被我修改過

**Comment by kkk682514** [comment]
請問一下現在的版本能正常使用嗎..?
我用iPad 3(New iPad iOS 8.4)打開後
一開始刷新全部都是寫null
![16395578_1549335571750872_1607128465_n](https://cloud.githubusercontent.com/assets/25432345/22423433/9c81cffc-e72c-11e6-913b-26e1e4183a15.png)
ExHentai 不能夠登入 
![16425295_1549335575084205_1905743677_n](https://cloud.githubusercontent.com/assets/25432345/22423444/a2d7d266-e72c-11e6-9d22-036123ebd19b.png)
麻煩協助了...

**Comment by DaidoujiChen** [comment]
Hello @kkk682514,

列表空白的問題關注在
https://github.com/DaidoujiChen/Dai-Hentai/issues/2

ex 無法登入已經在新的版本中有解, 但是還沒有被包成 ipa 檔案喔
