### ISSUE TITLE
Ex 从阅读漫画的状态返回到漫画列表时，漫画列表会被清空

### ISSUE THREAD

**Issue by anamewing** [DaidoujiChen/Dai-Hentai#69]
需要重新刷新一下才能看到漫画列表。

如果等待的时间足够长，也能看到漫画列表。
但是漫画列表总会被滚动到顶端，没有保存之前阅读到的位置。

**Comment by DaidoujiChen** [comment]
是在昨天 merge 進去的版本裡面產生的問題嗎 O3O?

**Comment by anamewing** [comment]
恩， `88b783c` 里没有这个问题，`feature/new_rule_for_exhentai_login` 上也没有这个问题。
目前 `master` 上的问题应该描述为：每次点 Back 回到漫画列表时，都要等好久 Hud 转圈；且无法维持之前漫画列表翻到的位置。

**Comment by DaidoujiChen** [comment]
我大概可以猜到為什麼 o3o"

**Comment by DaidoujiChen** [comment]
我會再來改 3q

**Comment by DaidoujiChen** [comment]
應該可以囉 >w<"
sorry
