### ISSUE TITLE
无法load出作品信息

### ISSUE THREAD

**Issue by w55039522** [DaidoujiChen/Dai-Hentai#70]
最近一段时间一直无法读取出作品信息(封面 名称) 不知是网站原因还是软件原因? 
还有就是只能加载出40页内容 后面的内容无法加载 以及点击下载后闪退

**Comment by DaidoujiChen** [comment]
Hello @w55039522,
跟 https://github.com/DaidoujiChen/Dai-Hentai/issues/2 是同一個問題喔

**Comment by w55039522** [comment]
到现在还是这个情况 请问怎么解决
软件装过3个版本的了 都出问题

**Comment by DaidoujiChen** [comment]
Hello @w55039522,

請問安裝的是哪一個版本呢?

**Comment by w55039522** [comment]
2.41 2.62 2.63

**Comment by w55039522** [comment]
2.64已解决 感谢菊苣:)

**Comment by DaidoujiChen** [comment]
O3Ob
