### ISSUE TITLE
好吧.....先來規劃版面跟資料存取吧...

### ISSUE THREAD

**Issue by DaidoujiChen** [DaidoujiChen/Dai-Hentai#73]
update: 2017 / 2 / 20, 調整一下頁面該有的行為

![2017-02-11 1 03 48](https://cloud.githubusercontent.com/assets/670441/22836074/fe3914ae-eff5-11e6-8345-807c09eddc0e.png)

列一下目前想到, 跟過去發生的問題

   * 資料庫這次應該會用 nosql 的 [couchbase](https://github.com/couchbase/couchbase-lite-ios)
      - 應該會分 `歷史瀏覽`
      - 跟 `下載` 這兩種存放
   * 為了避免過去切換列表或是已下載頁面就不知道看到哪邊的問題, 會用傳統的 tabbar 方式來做
   * 希望橫向直向都可以支援
   * 希望 phone / pad 都支援
   * 下載的部分應該需要優化, 過去的速度上, 或是顯示方法不夠理想
   * 所以目前總結起來可能會列出幾個 tab
      - 列表 (eh / ex)
      - 觀看歷史 (點擊進去看過的作品會被列到這個列表)
      - 最愛 (出門在外時沒這麼多時間下載, 可以先加入最愛)
      - 下載中 / 已下載 (覺得這兩個應該可以合為一體)
      - 設定

**Comment by carry0987** [comment]
全新介面？！Yo~~~
-- 
By Carry

**Comment by codexss** [comment]
不错啊，建议借鉴下 [EhViewer ](https://github.com/seven332/EhViewer) 的设计
另外再加上TAB应该会好看不少

**Comment by zhangyubaka** [comment]
换下 branch 编译一下（

**Comment by codexss** [comment]
还有一个开源项目我觉得双方作者可以合作一下
https://github.com/kayanouriko/E-HentaiViewer

**Comment by DaidoujiChen** [comment]
我覺得他做的版面比我漂亮 >w<"

**Comment by 1403249874** [comment]
怎么下载这个软件啊求教

**Comment by 1403249874** [comment]
必须要越狱嘛

**Comment by DaidoujiChen** [comment]
Hello @1403249874,

如果自己有 mac 電腦的話, 可以把源碼下載, 然後自己安裝到裝置中, 沒有的話就只能越獄囉 O3O

**Comment by 1403249874** [comment]
哦，好吧那真是谢谢了
