### ISSUE TITLE
一次解決橫向直向看模式

### ISSUE THREAD

**Issue by DaidoujiChen** [DaidoujiChen/Dai-Hentai#75]
用 `UICollectionView` 改一些設定就可以用同一個版面直接做到橫向直向觀看 O3O

橫向
<img width="487" alt="2017-02-15 12 43 39" src="https://cloud.githubusercontent.com/assets/670441/22938931/3061318a-f318-11e6-9430-f69e1d5e545f.png">

直向
<img width="487" alt="2017-02-15 12 43 39" src="https://cloud.githubusercontent.com/assets/670441/22938932/3067063c-f318-11e6-9903-e3fa95212453.png">

**Comment by xxf1995** [comment]
哇新版UI好棒

**Comment by carry0987** [comment]
這次的更新會移除掉以前下載的資料嗎？
-- 
By Carry

**Comment by DaidoujiChen** [comment]
會 這次是大改

**Comment by DaidoujiChen** [comment]
連 icon 我都想重做 O口O

**Comment by carry0987** [comment]
大改？想必流暢性及介面都會進化，期待～
-- 
By Carry

**Comment by carry0987** [comment]
對了，我有H@H，也有一個伺服器，如果可以幫助你用在新的版本上，隨時可以告訴我～
-- 
By Carry

**Comment by DaidoujiChen** [comment]
3q

**Comment by DaidoujiChen** [comment]
補圖, 其中橫向無 bar 應該可以解決之前很多人講說有些作品是橫頁的問題,
拿掉 bar 之後可以完整的全屏顯示, 體驗應該會好多

直向, 有 bar
<img width="487" alt="2017-02-20 10 19 45" src="https://cloud.githubusercontent.com/assets/670441/23128707/e231e476-f7ba-11e6-8ab3-2063e926e2f5.png">

直向, 無 bar
<img width="487" alt="2017-02-20 10 20 01" src="https://cloud.githubusercontent.com/assets/670441/23128708/e23971dc-f7ba-11e6-84ec-646e86868d4f.png">

橫向, 有 bar
<img width="779" alt="2017-02-20 10 20 23" src="https://cloud.githubusercontent.com/assets/670441/23128809/394b40d6-f7bb-11e6-8635-dd48d7a74ea2.png">

橫向, 無 bar
<img width="779" alt="2017-02-20 10 20 31" src="https://cloud.githubusercontent.com/assets/670441/23128810/3955279a-f7bb-11e6-9315-ede5a0dbebfa.png">
