### ISSUE TITLE
搜尋介面

### ISSUE THREAD

**Issue by DaidoujiChen** [DaidoujiChen/Dai-Hentai#76]
o.o 還在想要怎麼做
不過網頁真的寫的真的充滿槽點

![2017-02-20 11 19 16](https://cloud.githubusercontent.com/assets/670441/23130930/2bee191a-f7c3-11e6-9dc6-abe5e04a3a92.png)

`````
https://e-hentai.org/?f_doujinshi=1&f_manga=1&f_artistcg=1&
f_gamecg=1&f_western=1&f_non-h=1&f_imageset=1&f_cosplay=1&f_asianporn=1&
f_misc=1&f_search=chinese&f_apply=Apply+Filter&advsearch=1&f_sname=on&
f_stags=on&f_sr=on&f_srdd=2
`````

為什麼有的 flag 是 1 有的要是 on ??
為什麼不能統一??

**Comment by DaidoujiChen** [comment]
樸素的做法

<img width="487" alt="2017-02-24 2 40 23" src="https://cloud.githubusercontent.com/assets/670441/23293138/641a5edc-fa9f-11e6-8394-b196bcc8baf0.png">
<img width="487" alt="2017-02-24 2 41 16" src="https://cloud.githubusercontent.com/assets/670441/23293139/641fde66-fa9f-11e6-941a-0467aea88d89.png">
<img width="487" alt="2017-02-24 2 41 20" src="https://cloud.githubusercontent.com/assets/670441/23293140/642017be-fa9f-11e6-8635-28313c37da2e.png">

**Comment by anamewing** [comment]
既然 Chinese 如此常用，要不要给它专门加一个 filter？
进一步地，是否可以保存常用的过滤器列表，显示在搜索界面？

**Comment by DaidoujiChen** [comment]
好喔 那我來想想怎麼做

**Comment by DaidoujiChen** [comment]
對於搜尋有兩種優化

 - 從某一部作品可以選擇 `用相關字詞搜尋`, 可以利用該部作品, 找到類似的類型
 - 搜尋介面中, 會統計最近觀看過的 10 部作品中的關鍵字或是 tag, 可以直接勾選加入
