### ISSUE TITLE
登录不上去Ex-hentai

### ISSUE THREAD

**Issue by 1793907272** [DaidoujiChen/Dai-Hentai#77]
密碼帳號都有，沒有開VPN

**Comment by DaidoujiChen** [comment]
Hello @1793907272 

請問你用的是哪一個版本呢?

**Comment by 1793907272** [comment]
@DaidoujiChen 
应该是2.64的

**Comment by DaidoujiChen** [comment]
2.64 再登入失敗的時候, 應該會有一個提示窗, 可以選擇用 webview 登入,
app 會開啟一個原來網頁的頁面讓你登入, 如果連網頁都打不開的話, 應該就是被牆了吧 O3O

**Comment by 1793907272** [comment]
@DaidoujiChen 好的，我去试试。
帐号密码是forums的帐号密码吧。

**Comment by DaidoujiChen** [comment]
對的, 就是直接使用原來的網站登入

**Comment by 1793907272** [comment]
试了一下，没有显示网页登陆。
提示是：“也许哪边出错咯”

**Comment by DaidoujiChen** [comment]
我大概的錄製了一段影片, 2.64 應該會在登入失敗的時候跳出 "或許我可以試試 WebView O3O" 的提示

[![IMAGE ALT TEXT](http://img.youtube.com/vi/FXsAXCBTiUs/0.jpg)](http://www.youtube.com/watch?v=FXsAXCBTiUs)

**Comment by 1793907272** [comment]
或許我這個可能不是2.64。
我重新安裝試試。

**Comment by DaidoujiChen** [comment]
關掉先 O3Ob
