### ISSUE TITLE
想問下3.0版本的還在測試階段麼

### ISSUE THREAD

**Issue by ruizhipeng** [DaidoujiChen/Dai-Hentai#78]
看了下最近更新的都是這個分支 如果允許的話 能不能抽空做一個3.0版本呢 順帶一提我是linux 不知道編譯環境能不能搭建出來。。。。 如果有打擾就關閉吧。。。。 感謝作者了

**Comment by DaidoujiChen** [comment]
Hello @ruizhipeng,

目前是測試的階段, 超測試的, 雖然我自己感覺體驗還不錯, 但是沒有下載跟紀錄過看過什麼, 所以目前只能當作看當下本子的工具而已 >w<"

linux 應該是不行的說, 比如說用 jenkins 的時候, 還是要有台比如說 mac mini 來當 slave 幫 build, 才可以把 ipa build 出來 o3o"

說起來我也蠻想找一個 cd 的服務, 可以自動幫我 build 完之後把 ipa 上傳的, OwO 正在找就是了
