### ISSUE TITLE
开启横向浏览时无法删除漫画

### ISSUE THREAD

**Issue by thsh527** [DaidoujiChen/Dai-Hentai#79]
2.64版，我是iOS8.4

**Comment by DaidoujiChen** [comment]
是.....但是有點懶惰修...
```
_(:3 」∠ )_
```

**Comment by carry0987** [comment]
別修了，直接再新版解決就行啦～
-- 
By Carry

**Comment by DaidoujiChen** [comment]
新版的生長進度緩慢 Q口Q

**Comment by carry0987** [comment]
目前卡在哪裡？
-- 
By Carry

**Comment by DaidoujiChen** [comment]
卡在時間太少 Q口Q

**Comment by carry0987** [comment]
啊....我都忘了前輩還有工作.....
-- 
By Carry

**Comment by DaidoujiChen** [comment]
可以點這個試試看 -> [試用](https://appetize.io/embed/qk23vcyrmbtecy7n12h6118wa4?device=iphone7&scale=100&orientation=portrait&osVersion=10.0&deviceColor=white) 其實速度比現有版本快很多, 只是斷手斷腳這樣

**Comment by carry0987** [comment]
斷手斷腳XD....
其實只是還沒完善吧？沒出現什麼大Bug就好啦
-- 
By Carry

**Comment by DaidoujiChen** [comment]
斷手斷腳就是目前只可以搜尋跟看.....
沒有紀錄之類的 所以看過的東西雖然會存在裝置裡面
但是沒有目錄可以查閱
Q口Q

**Comment by carry0987** [comment]
舊版的有目錄嗎？
-- 
By Carry

**Comment by DaidoujiChen** [comment]
就是像說比如 "已下載" 這樣的列表
目前在做的版本是想把 "有看過" 的也整理一個列表
然後還有一些可能是 "我的最愛" 之類的列表

**Comment by carry0987** [comment]
喔喔，懂了


DaidoujiChen <notifications@github.com> 於 2017年3月21日 下午6:25 寫道：
