### ISSUE TITLE
反馈几个问题

### ISSUE THREAD

**Issue by loo0** [DaidoujiChen/Dai-Hentai#81]
软件：2.64.  使用机器：ipad pro12.9
实在感谢，ios终于能看ehentai了，win板子可以安心出掉了
几个小问题反馈，现在用也很棒了，但希望以后能逐渐修改下
1，下载的时候选自定分类就闪退
2，左侧菜单看不到选项，屏幕右划之后出来的是空白的一条，再向右划动才能看到选项内容的提示文字，是在12。9的机器上汉字提示错位？按着文字的大概问题点空白就能点到正常的功能上。
3，不能自动横屏？因为pro经常插键盘用，能有横屏下显示完整一页就好了
4，背景下载怎么开？被弹窗提示弹的烦了，给了gps权限，但后台之后下载还是就断了啊？
5，如果能想ehviewer一样能看每个漫画标签，然后直接搜索标签就好了

**Comment by DaidoujiChen** [comment]
Hello @loo0,

必須先羨慕你有 12.9 的 ipad Q口Q"

目前正在進行 3.0 的開發, 希望是可以改掉 2.x 的一些問題,
但是同時可能就比較沒有辦法回來修舊版本的 bug
雖然進度有點慢, 不過可以看一下 

https://github.com/DaidoujiChen/Dai-Hentai/tree/3.0_master

感謝你的意見

**Comment by carry0987** [comment]
人類滅絕計畫3.0 ww
-- 
By Carry

**Comment by loo0** [comment]
了解  @DaidoujiChen  
pro也是砸锅卖铁买的二手的，使用体验倒是很值。
那就期待3.0了！

**Comment by DaidoujiChen** [comment]
這個就先關掉囉 O3Ob
