### ISSUE TITLE
Cydia Impactor安装不上ipa

### ISSUE THREAD

**Issue by chesterlyd** [DaidoujiChen/Dai-Hentai#83]
~~用Cydia Impactor安装ipa一直卡在GeneratingApplicationMap，AppleID 已经关了双重验证~~
安装完图标显示的是ios 标准图标
![21r58picfiv_1024](https://cloud.githubusercontent.com/assets/10460338/25315670/98b732ae-288b-11e7-8c0f-0776a0202222.png)

**Comment by DaidoujiChen** [comment]
Hello @LYDfalse,

不好意思, 請問一下最後是有裝上去沒有圖示, 還是裝上去了無法使用 O3O?
然後請問是裝哪一個版本的 ipa 呢?
謝謝

**Comment by chesterlyd** [comment]
ipa安装成功了，图标显示不正常
安装的是3.0_20170416

**Comment by DaidoujiChen** [comment]
Hello @LYDfalse,

是呦 >w<" 目前 3.0 都還沒有放圖示
感謝你可以玩 3.0

**Comment by chesterlyd** [comment]
还是非常感谢能让ios也有专门的app

**Comment by DaidoujiChen** [comment]
那我先關上這個囉 O3O
3.0 如果有使用上的問題
再麻煩跟我說
謝謝

**Comment by carry0987** [comment]
所以，3.0不會覆蓋舊版的？會變成第二個軟體？
-- 
By Carry

**Comment by DaidoujiChen** [comment]
對 O3O

**Comment by DaidoujiChen** [comment]
@carry0987 

也可以裝 3.0 來試玩看看呦
