### ISSUE TITLE
Does not work well with iOS 11 beta

### ISSUE THREAD

**Issue by uetcis** [DaidoujiChen/Dai-Hentai#85]
在EXHENTAI或EHENTAI界面，点击搜索图标会提示跳转页码而非提示搜索

**Comment by DaidoujiChen** [comment]
Hello @CaptainYukinoshitaHachiman,
O口O 我還沒有試用過 ios11

**Comment by uetcis** [comment]
2333333
我现在试了下找到了问题所在
我发现只要你点到了Navigation Bar上的任何东西，就都会弹出跳转页码的提示
我试着把显示搜索界面的code放到了viewDidLoad里，每次进入view自动弹出搜索界面，没有任何问题。
所以我在想这会不会是Xcode9编译器的问题还有待测试。
（所以说为什么不用StoryBoard233）

**Comment by uetcis** [comment]
所以说希望能够看下这个问题233333
或者如果你懒的话说不定周末有空我来拿Swift写个UI（不会OC orz）

**Comment by uetcis** [comment]
还有dalao有准备改用Swift的想法吗(￣▽￣)

**Comment by DaidoujiChen** [comment]
Hello @CaptainYukinoshitaHachiman,

我在 swift 2.3 的時候寫過一個版本上架 app store
但是改 swift 3.0 的時候就懶得改了 =w="

**Comment by DaidoujiChen** [comment]
3.0 的版本是用 storyboard 喔 O3O
但是感覺其實沒有 xib 來的靈活

**Comment by uetcis** [comment]
233333
Swift2到3改了好多Orz
现在Swift4改了什么我还没去看
总之麻烦dalao看一下吧，如果你那边也有问题我觉得就得去file一个radar了

**Comment by DaidoujiChen** [comment]
Hello @CaptainYukinoshitaHachiman,

這個我先關掉囉, 目前 ios11 應該是 ok 的.

**Comment by uetcis** [comment]
好的，我来试试😀
