### ISSUE TITLE
添加iPhone X支持

### ISSUE THREAD

**Issue by uetcis** [DaidoujiChen/Dai-Hentai#87]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/25654046/34449617-0f0ffd28-ed35-11e7-9ee7-4110dcf0b785.png">
如图，在iPhone X下选择“问题回报”后左上角会显示出超出了SafeArea的Done button

**Comment by DaidoujiChen** [comment]
在 3.0 有支援呦 =w=
2.x 我不太想動了
