### ISSUE TITLE
版本號3.1_20180210 iOS 8.1.2閃退

### ISSUE THREAD

**Issue by carry0987** [DaidoujiChen/Dai-Hentai#91]
iPhone 5 8.1.2 已越獄

**Comment by gabmak** [comment]
iPad mini 2 8.1.2 已越獄 也閃退
是否已drop iOS8 support?

**Comment by gabmak** [comment]
Dai-Hentai (tw.daidouji.Dai-Hentai): *** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named UILayoutGuide'

這是從crash report 中抓出來

**Comment by DaidoujiChen** [comment]
我試試

**Comment by DaidoujiChen** [comment]
感覺這是為了支援 iPhoneX 衍伸出來的 issue

**Comment by carry0987** [comment]
該不會....8.X不支援 ?!

**Comment by gabmak** [comment]
Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector applicationDidFinishLaunching:

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector launchFromLocation:

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector launchFromLocation:context:

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector launchFromLocation:

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector launchFromLocation:context:

Sat Feb 24 02:10:22 2018: Dai-Hentai (tw.daidouji.Dai-Hentai): CoreFoundation 1141.160000 detected, appears to be iOS 7/8.

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector slowDownFactor

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector backlightFadeDuration

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector setIsEditing:

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector _beginEditing

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector _stopEditing

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector presentHUDView:autoDismissWithDelay:

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector useNewBounce

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector dismissAnimated:

Sat Feb 24 02:10:22 2018: Dai-Hentai (com.apple.console): MS:Warning: nil class argument for selector useHighQualityGraphics

**Comment by gabmak** [comment]
9.3.3 iPhone 6 plus 已越獄 就沒有這個問題

**Comment by carry0987** [comment]
@gabmak 不會吧.....

**Comment by gabmak** [comment]
關於2.x 及 3.x 進入閱讀版面時閃退問題, 只要到E-hentai及Exhentai 的設定 將default profile 的 "Multi-Page Viewer" 關掉 就可以正常訪問
https://exhentai.org/uconfig.php
https://e-hentai.org/uconfig.php
這是因為最近 EH 那邊把config放到上了server 而不是以往的cookie

**Comment by DaidoujiChen** [comment]
3.x 也會嗎?
我自己也是在用 3.x 的說
OoO

**Comment by DaidoujiChen** [comment]
上面那個會閃退的問題確實是因為版面的某樣東西不支援 iOS 8.x 只支援 9.0 以上 QwQ

**Comment by carry0987** [comment]
QQ....3.1果然不相容於ios8嗎....

**Comment by DaidoujiChen** [comment]
主要是有些要適配 iphoneX 的版面很麻煩

**Comment by carry0987** [comment]
大大，iOS 8的部分就使用2.X版的對吧？

**Comment by DaidoujiChen** [comment]
Hello @carry0987 

2.x 感覺 bug 蠻多的 =w="

**Comment by carry0987** [comment]
@gabmak Thanks !

**Comment by carry0987** [comment]
@DaidoujiChen 不如不管2.X的Bug,只要讓2.X可以連exh就行了....畢竟iOS 8.X 只能用 2.X版 (或者叫使用者自己改exh的設定？)

**Comment by DaidoujiChen** [comment]
Hello @carry0987,

我會找時間想一下, 3qq.

**Comment by kkk682514** [comment]
請問有人iOS12無法用Cydia Impactor簽的嗎@@
0.9.45可以過 不過程式打不開(會閃退)
0.9.46會直接crash@@

**Comment by asdchange7** [comment]
大佬 能支援ios12吗

**Comment by asdchange7** [comment]
或者 上架别的区的苹果商店可以吗  ios没有越狱啊

**Comment by kkk682514** [comment]
@pjxcsrt321 
ios12親測可用( iphone 7+ 12.0)
無越獄用impactor每個禮拜簽一次就好
不過用起來有時候搜尋按鈕會跑版@@(一樣在右上角不過icon變一半(大概))

**Comment by asdchange7** [comment]
这个 iphone8p闪退 不知道为什么 我想既然不行还顺便升级了12.0.1


发自 iPhone 版 Yahoo 邮箱


星期五, 十月 12, 2018, 19:58 于 kkk682514 <notifications@github.com>写道：


@pjxcsrt321
ios12親測可用( iphone 7+ 12.0)
無越獄用impactor每個禮拜簽一次就好
不過用起來有時候搜尋按鈕會跑版@@(一樣在右上角不過icon變一半(大概))

**Comment by gabmak** [comment]
iPhone 7 plus iOS12.0.1 剛剛試過也沒有問題

@pjxcsrt321 
可能是因為impactor的版本或是未在設定中點選信任開發者

**Comment by asdchange7** [comment]
omg 各位 imp失败 应该是版本的问题 我 0.95所以不行 升级到 0.97完美 12.0.1在这里 假设上架了appstore 我一定会出力的

**Comment by asdchange7** [comment]
> iPhone 7 plus iOS12.0.1 剛剛試過也沒有問題
> 
> @pjxcsrt321
> 可能是因為impactor的版本或是未在設定中點選信任開發者

emm 是imp版本低了 0.95 最高是0.97 现在ok了

**Comment by codexss** [comment]
捐助作者可以给签名版的ipa(ง ͠° ͟ل͜ ͡°)ง

发自我的 iPhone

**Comment by DaidoujiChen** [comment]
喔 對了 而且前一陣子我發現一件很煩的事情
`tw.daidouji.Dai-Hentai` 已經被別人用走在 app store 裡面
所以我沒辦法叫這個名字送審 o.o
超無言

**Comment by codexss** [comment]
可以开一波testflight(((o(*ﾟ▽ﾟ*)o)))

发自我的 iPhone

**Comment by carry0987** [comment]
> 喔 對了 而且前一陣子我發現一件很煩的事情
> `tw.daidouji.Dai-Hentai` 已經被別人用走在 app store 裡面
> 所以我沒辦法叫這個名字送審 o.o
> 超無言


這根本針對你，太扯了，居然抄襲這個名字？

**Comment by DaidoujiChen** [comment]
@carry0987 

可能對方也是無心的啦 OwO
只是如果我換個名字 就又會變成兩個 app 了這樣

**Comment by DaidoujiChen** [comment]
先關掉這個 issue 囉 OwO
