### ISSUE TITLE
在浏览主页的时候上下的选项栏会消失

### ISSUE THREAD

**Issue by xingfanxia** [DaidoujiChen/Dai-Hentai#92]
如果一直向下浏览搜索结果页面的话有时候上下的选项栏会消失（历史，下载，设定，搜索那些），只能重启app修复

**Comment by DaidoujiChen** [comment]
你說的是 3.x 對吧? 如果是的話我覺得還蠻嚴重的 我會再試試看

**Comment by DaidoujiChen** [comment]
還是問一下裝置跟壞掉時候的截圖好了 =w= 感恩

**Comment by xingfanxia** [comment]
![img_1051](https://user-images.githubusercontent.com/8936233/37203744-51bc1558-2354-11e8-9cdc-af0af0e79db4.png)

设备是 Iphone X 11.2.6
今天pull了重新试了一下，发现更新之后是看完一本返回浏览所有书本的时候下面的选项栏会消失。（见图）
我是不是该打码..

**Comment by DaidoujiChen** [comment]
好喔 如果是 ipx 的問題的話我比較有測試的方向 我來試試看喔 3qq

**Comment by DaidoujiChen** [comment]
先試試看這個解吧, 不過感覺我的 ip6s 實機上面會有一點怪怪的, 所以引發的步驟應該是

 - 點擊隨便一部作品
 - 在看作品的頁面裡面點擊任一處讓上下的 bar 消失
 - 利用手勢動作, 從邊緣滑動, 離開這個頁面
 - 回到列表頁時, bar 有可能會不見

這樣對吧?

**Comment by xingfanxia** [comment]
恩应该是的，我现在试试看

**Comment by xingfanxia** [comment]
试了几次，应该是修复了！感谢

**Comment by DaidoujiChen** [comment]
@xxf1995 

感恩 >w<
