### ISSUE TITLE
装回来发现又搜索不到东西了

### ISSUE THREAD

**Issue by DDG25** [DaidoujiChen/Dai-Hentai#93]
这两天试了一下不完全越狱，总算又装了回来，然后发现又搜索不到东西，以前换个版本就行了，但这次试了2.4、2.6X、3.1都没用，请问有办法解决吗？

**Comment by DaidoujiChen** [comment]
因為我使用上面搜尋好像沒有發生過問題
請問是在牆內嗎? 會不會跟 vpn 之類的有關係?

**Comment by DDG25** [comment]
墙内但一直挂着SS。以前是用得好端端的突然搜不到，换个版本就正常。
不过找到问题了，不知为啥现在路由直接挂的SS不行，要机器自己挂才能用。

**Comment by DaidoujiChen** [comment]
畢竟牆還是很厲害的 =w="

有找到幾篇像是

https://github.com/shadowsocks/shadowsocks/issues/1060

https://github.com/shadowsocks/shadowsocks/issues/1138

感覺都是 ss 有時候會有被牆抓住的感覺

**Comment by DaidoujiChen** [comment]
Hello @DDG25 

這個是網路問題的話我就先關掉囉 : )

**Comment by DDG25** [comment]
好的，谢谢~~
