### ISSUE TITLE
觀看頁數直接跳頁產生的 crash 問題

### ISSUE THREAD

**Issue by DaidoujiChen** [DaidoujiChen/Dai-Hentai#98]
- 隨便找一部有壞頁的作品 (? 好像也不是常常有
 - 看超過壞掉的那一頁
 - 退出該部作品
 - 重新進入時, 詢問是否跳到上次看的那一頁
 - 選擇是, 然後 crash

**Comment by BIake123** [comment]
請問在Exh搜尋之後把搜尋列的刪掉，再回到列表會顯示找不到相關作品，重裝App再試一次也一樣要怎麼處理

**Comment by DaidoujiChen** [comment]
Hello @BIake123 

不一樣的問題可能要麻煩幫我另外開一個 issue 呦, 而且你的是 2.x 的問題 O3O?
