### ISSUE TITLE
在Exh搜尋之後把搜尋列的刪掉，回列表會顯示找不到相關作品 3.1 ios 11.2.6

### ISSUE THREAD

**Issue by BIake123** [DaidoujiChen/Dai-Hentai#99]
請問在Exh搜尋之後把搜尋列的刪掉，再回到列表會顯示找不到相關作品，重裝App再試一次也一樣要怎麼處理

**Comment by DaidoujiChen** [comment]
Hello @BIake123 

下面的步驟是按照你的敘述做出來的行為, 列表頁面左上角無顯示 `Ex` 表示說已經在 Exh 下, 第一次搜尋 `moe`

![img_4043](https://user-images.githubusercontent.com/670441/37090002-a0e8ecb8-223d-11e8-8787-4b92d591252b.PNG)

結果如圖

![img_4041](https://user-images.githubusercontent.com/670441/37090025-b0cb6d68-223d-11e8-880c-c5b5252e864d.PNG)

後來將搜尋的內容清除掉

![img_4044](https://user-images.githubusercontent.com/670441/37090046-c5a70b66-223d-11e8-8800-962397365f11.PNG)

再次做搜尋

![img_4042](https://user-images.githubusercontent.com/670441/37090065-d5ab8f14-223d-11e8-91d8-3ac1b680299b.PNG)

還是有內容, 請問這是你所描述的狀況嗎? 還是說換一個網路環境試試看呢? 感恩

**Comment by wangtao03** [comment]
抓數據看了下 顯示 "找不到相關作品" 時 在搜索返回后並未繼續訪問 exhentai.org/api.php
更換台灣、日本、韓國 VPN 均有此情況

**Comment by DaidoujiChen** [comment]
@wangtao03 

好呦, 我會從這個方向去看看, 感恩

**Comment by DaidoujiChen** [comment]
Hello @BIake123 & @wangtao03 

我的回覆在另外一篇裡面

https://github.com/DaidoujiChen/Dai-Hentai/issues/100#issuecomment-372039624

如果有興趣的話也可以試試看呦 O3O

**Comment by DaidoujiChen** [comment]
@BIake123 

在 #100 那邊看起來已經解掉這個問題囉 >w<
感謝你的支持
這個問題我就先關掉囉
